/**
 * Pure SVG builders for every brand export. No rendering and no file I/O
 * happen here (export.ts does that), so tests can check the output strings.
 * Geometry rules come from .design/brand/BRAND_BRIEF.md §3, §5 and §6.
 */

import type { Master, MasterPath } from "./masters";

/** Trim float noise so the same input always prints the same SVG. */
export function fmt(n: number): string {
  return String(Number(n.toFixed(4)));
}

export function pathElements(paths: MasterPath[], fill: string, indent = ""): string {
  return paths
    .map(
      (p) =>
        `${indent}<path fill="${fill}" fill-rule="${p.fillRule}" clip-rule="${p.fillRule}" d="${p.d}"/>`,
    )
    .join("\n");
}

/**
 * The transform that maps a master's viewBox onto a box at (x, y) that is
 * `width` wide. Identity parts are left out, so the 1000-unit mark placed in
 * a 1000 box prints no transform at all.
 */
export function placement(m: Master, x: number, y: number, width: number): string {
  const [vx, vy, vw] = m.viewBox;
  const s = width / vw;
  const parts: string[] = [];
  if (x !== 0 || y !== 0) parts.push(`translate(${fmt(x)} ${fmt(y)})`);
  if (s !== 1) parts.push(`scale(${fmt(s)})`);
  if (vx !== 0 || vy !== 0) parts.push(`translate(${fmt(-vx)} ${fmt(-vy)})`);
  return parts.join(" ");
}

function placed(m: Master, fill: string, x: number, y: number, width: number): string {
  const t = placement(m, x, y, width);
  const body = pathElements(m.paths, fill, t ? "    " : "  ");
  return t ? `  <g transform="${t}">\n${body}\n  </g>` : body;
}

/** A master recoloured on its own canvas: the SVG exports (paper, ink, currentColor). */
export function artworkSvg(m: Master, fill: string): string {
  const [vx, vy, vw, vh] = m.viewBox;
  return [
    `<svg xmlns="http://www.w3.org/2000/svg" viewBox="${fmt(vx)} ${fmt(vy)} ${fmt(vw)} ${fmt(vh)}" width="${fmt(vw)}" height="${fmt(vh)}">`,
    `  <title>Moduo</title>`,
    pathElements(m.paths, fill, "  "),
    "</svg>",
    "",
  ].join("\n");
}

/**
 * The mark on a square tile in a 1000-unit box: favicons, touch icons,
 * avatars. `radius` 0 gives a full square (iOS and social sites crop their
 * own shape). `markScale` 1 keeps the mark's own 1000-unit box, which is how
 * the shipped favicon and icon have always placed it.
 */
export function tileSvg(opts: {
  mark: Master;
  background: string;
  fill: string;
  radius: number;
  markScale?: number;
}): string {
  const scale = opts.markScale ?? 1;
  const size = 1000 * scale;
  const offset = (1000 - size) / 2;
  const rx = opts.radius > 0 ? ` rx="${fmt(opts.radius)}"` : "";
  return [
    `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1000 1000" width="1000" height="1000">`,
    `  <rect width="1000" height="1000"${rx} fill="${opts.background}"/>`,
    placed(opts.mark, opts.fill, offset, offset, size),
    "</svg>",
    "",
  ].join("\n");
}

/**
 * Legacy (pre-macOS 26) app icon: a 1024 canvas with its own rounded tile,
 * because older macOS doesn't mask icons. The mark's 1000-unit box sits
 * centred at (12, 12), about 70% of the width, as in the shipped icon.
 */
export function macosIconSvg(mark: Master, background: string, fill: string): string {
  return [
    `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1024 1024" width="1024" height="1024">`,
    "  <!--",
    "    Generated by `bun run brand:export` from brand/masters/mark.svg. Do not edit;",
    "    edit the master and re-export, then run `bun scripts/icons/build-macos-icon.ts`.",
    "    Tile corner radius ≈ 22.5% of the width (Apple's guide); the mark's 1000-unit",
    "    box sits centred at (12, 12), so the mark spans ~70% of the canvas.",
    "  -->",
    `  <rect width="1024" height="1024" rx="230" ry="230" fill="${background}"/>`,
    placed(mark, fill, 12, 12, 1000),
    "</svg>",
    "",
  ].join("\n");
}

/** macOS 26 Liquid Glass foreground layer: the same placement, no tile (the system draws it). */
export function glassLayerSvg(mark: Master, fill: string): string {
  return [
    `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1024 1024" width="1024" height="1024" fill="none">`,
    "  <!--",
    "    Generated by `bun run brand:export` from brand/masters/mark.svg. Do not edit;",
    "    edit the master and re-export, then run `bun run icon:liquid`.",
    "    Transparent: icon.json's fill and the system squircle make the tile.",
    "  -->",
    placed(mark, fill, 12, 12, 1000),
    "</svg>",
    "",
  ].join("\n");
}

/**
 * Share-image base (1200×630): Canvas black with the lockup top-left. Pages
 * add their own line and product frame on top (brief §13).
 */
export function ogBaseSvg(lockup: Master, background: string, fill: string): string {
  const [, , vw, vh] = lockup.viewBox;
  const height = 40;
  const width = (height * vw) / vh;
  return [
    `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1200 630" width="1200" height="630">`,
    `  <rect width="1200" height="630" fill="${background}"/>`,
    placed(lockup, fill, 80, 80, width),
    "</svg>",
    "",
  ].join("\n");
}

/**
 * A master fitted into a fixed canvas: scaled to fit, left-aligned, vertically
 * centred, transparent around it.
 */
export function canvasSvg(opts: {
  master: Master;
  fill: string;
  width: number;
  height: number;
}): string {
  const [, , vw, vh] = opts.master.viewBox;
  const scale = Math.min(opts.width / vw, opts.height / vh);
  const y = (opts.height - vh * scale) / 2;
  const t = placement(opts.master, 0, y, vw * scale);
  return [
    `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${opts.width} ${opts.height}" width="${opts.width}" height="${opts.height}">`,
    `  <g${t ? ` transform="${t}"` : ""}>`,
    pathElements(opts.master.paths, opts.fill, "    "),
    "  </g>",
    "</svg>",
    "",
  ].join("\n");
}

function pathsLiteral(m: Master): string {
  return m.paths
    .map((p) => `  {\n    d: "${p.d}",\n    fillRule: "${p.fillRule}",\n  },`)
    .join("\n");
}

function viewBoxText(m: Master): string {
  return m.viewBox.map(fmt).join(" ");
}

/**
 * The generated TS module the ModuoMark component renders from. Its output is
 * already Biome-formatted (the drift test compares it byte for byte). The
 * small drawing falls back to the standard mark until mark-small.svg exists.
 */
export function markModule(mark: Master, small: Master | null): string {
  const smallMark = small ?? mark;
  const type = 'readonly { d: string; fillRule: "evenodd" | "nonzero" }[]';
  return [
    "// Generated by `bun run brand:export` from brand/masters/mark.svg (and mark-small.svg).",
    "// Do not edit by hand: change the master and re-export (see brand/README.md).",
    "",
    `export const MODUO_MARK_VIEWBOX = "${viewBoxText(mark)}";`,
    "",
    `export const MODUO_MARK_PATHS: ${type} = [`,
    pathsLiteral(mark),
    "];",
    "",
    "/** The small-size drawing, only for marks displayed under 24 px. */",
    `export const MODUO_MARK_SMALL_VIEWBOX = "${viewBoxText(smallMark)}";`,
    "",
    `export const MODUO_MARK_SMALL_PATHS: ${type} = [`,
    pathsLiteral(smallMark),
    "];",
    "",
  ].join("\n");
}
