-- Stub of production for supabase/probes/tasks-assignee.probe.sql (TV-D1).
-- The repo can't bootstrap a database (supabase/AGENTS.md), so this recreates
-- what 20261008150000_tasks_assignee_creator.sql touches, as production has it
-- on 2026-10-08 (project wtoonrvuqumihpkbvwvs), after PRIV-2a
-- (20261008013000) and key_writes_act_as_creator (20261008020039):
--   * tables and their delete rules, from the PRIV-2a stub (read from the
--     catalog), with the columns TV-D1 reads: every tasks column, activity
--     timestamps, API-key scopes;
--   * every function body exactly as production has it (pg_get_functiondef),
--     including the ones the migration redefines, so the probe starts from
--     the real "before";
--   * every trigger production has on these tables, except the insert-time
--     sharing seeds (the probe sets members' perms and grants itself).
-- Generated by the TV-D1 session; regenerate rather than hand-edit when
-- production changes.

SET check_function_bodies = off;

CREATE EXTENSION IF NOT EXISTS pgcrypto;

DO $$ BEGIN CREATE ROLE anon NOLOGIN; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE ROLE authenticated NOLOGIN; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE ROLE service_role NOLOGIN BYPASSRLS; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
-- Like Supabase: every new function in public is executable by these roles
-- directly (not through PUBLIC), so a migration must revoke them by name.
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT EXECUTE ON FUNCTIONS TO anon, authenticated, service_role;

CREATE SCHEMA auth;
CREATE TABLE auth.users (id uuid PRIMARY KEY, email text);
CREATE FUNCTION auth.uid() RETURNS uuid LANGUAGE sql STABLE AS $$
  SELECT (nullif(current_setting('request.jwt.claims', true), '')::jsonb ->> 'sub')::uuid
$$;

-- ── Tables ──────────────────────────────────────────────────────────────────

CREATE TABLE public.profiles (
  id uuid PRIMARY KEY REFERENCES auth.users (id) ON DELETE CASCADE,
  display_name text NOT NULL DEFAULT '',
  stripe_customer_id text
);
CREATE TABLE public.workspaces (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  name text NOT NULL,
  owner_id uuid NOT NULL REFERENCES public.profiles (id) ON DELETE CASCADE,
  deleted_at timestamptz
);
CREATE TABLE public.workspace_members (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  workspace_id uuid NOT NULL REFERENCES public.workspaces (id) ON DELETE CASCADE,
  user_id uuid NOT NULL REFERENCES public.profiles (id) ON DELETE CASCADE,
  role text NOT NULL DEFAULT 'member',
  perms text[] NOT NULL DEFAULT '{}',
  permissions_email text,
  joined_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (workspace_id, user_id)
);
CREATE TABLE public.workspace_share_defaults (workspace_id uuid PRIMARY KEY, buckets text);
CREATE TABLE public.workspace_invites (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  workspace_id uuid NOT NULL REFERENCES public.workspaces (id) ON DELETE CASCADE,
  email text NOT NULL,
  status text NOT NULL DEFAULT 'pending',
  created_by uuid REFERENCES public.profiles (id) ON DELETE SET NULL
);

CREATE TABLE public.notes (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  workspace_id uuid NOT NULL REFERENCES public.workspaces (id) ON DELETE CASCADE,
  created_by uuid REFERENCES public.profiles (id) ON DELETE SET NULL,
  title text NOT NULL DEFAULT '',
  parent_id uuid REFERENCES public.notes (id) ON DELETE SET NULL,
  deleted_at timestamptz,
  share_mode text NOT NULL DEFAULT 'custom',
  share_scope text NOT NULL DEFAULT 'private',
  share_permission text NOT NULL DEFAULT 'edit',
  workspace_shared boolean NOT NULL DEFAULT false,
  publish_token text,
  published_at timestamptz
);
CREATE TABLE public.note_updates (
  id bigserial PRIMARY KEY,
  workspace_id uuid NOT NULL,
  note_id uuid NOT NULL REFERENCES public.notes (id) ON DELETE CASCADE,
  update_b64 text NOT NULL DEFAULT ''
);
-- note_shares_note_id_fkey exists on production, but no migration records its
-- delete rule; the stub takes the strictest one.
CREATE TABLE public.note_shares (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  note_id uuid NOT NULL REFERENCES public.notes (id),
  workspace_id uuid NOT NULL,
  user_id uuid NOT NULL REFERENCES public.profiles (id) ON DELETE CASCADE
);
CREATE TABLE public.exposed_notes (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  note_id text NOT NULL,
  title text NOT NULL DEFAULT ''
);

CREATE TABLE public.buckets (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  workspace_id uuid NOT NULL REFERENCES public.workspaces (id) ON DELETE CASCADE,
  owner_id uuid,
  name text NOT NULL,
  is_system boolean NOT NULL DEFAULT false,
  position text NOT NULL DEFAULT 'a0',
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  deleted_at timestamptz
);
CREATE UNIQUE INDEX buckets_one_system_per_owner_idx
  ON public.buckets (workspace_id, owner_id) WHERE is_system AND deleted_at IS NULL;
-- Production's columns, defaults and checks (no foreign key on owner_id).
CREATE TABLE public.tasks (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  workspace_id uuid NOT NULL REFERENCES public.workspaces (id) ON DELETE CASCADE,
  owner_id uuid DEFAULT auth.uid(),
  bucket_id uuid NOT NULL REFERENCES public.buckets (id) ON DELETE RESTRICT,
  title text NOT NULL DEFAULT '',
  description text NOT NULL DEFAULT '',
  due_date timestamptz,
  scheduled_at timestamptz,
  duration_minutes integer,
  recurrence jsonb,
  energy_level text CHECK (energy_level IN ('low', 'medium', 'high')),
  status text NOT NULL DEFAULT 'todo' CHECK (status IN ('todo', 'in_progress', 'done', 'archived')),
  committed_for date,
  commit_order integer,
  reschedule_count integer NOT NULL DEFAULT 0,
  position text NOT NULL DEFAULT '',
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  deleted_at timestamptz,
  priority text CHECK (priority IN ('low', 'medium', 'high')),
  parent_id uuid REFERENCES public.tasks (id) ON DELETE SET NULL,
  time_spent_seconds integer NOT NULL DEFAULT 0 CHECK (time_spent_seconds >= 0),
  CONSTRAINT tasks_parent_not_self CHECK (parent_id IS NULL OR parent_id <> id)
);
CREATE TABLE public.task_relations (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  workspace_id uuid NOT NULL,
  blocker_task_id uuid NOT NULL REFERENCES public.tasks (id) ON DELETE CASCADE,
  blocked_task_id uuid NOT NULL REFERENCES public.tasks (id) ON DELETE CASCADE
);
CREATE TABLE public.task_time_blocks (
  workspace_id uuid PRIMARY KEY REFERENCES public.workspaces (id) ON DELETE CASCADE,
  blocks jsonb NOT NULL DEFAULT '{}'::jsonb,
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE public.companies (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  workspace_id uuid NOT NULL REFERENCES public.workspaces (id) ON DELETE CASCADE,
  owner_id uuid,
  name text NOT NULL DEFAULT '',
  deleted_at timestamptz
);
CREATE TABLE public.contacts (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  workspace_id uuid NOT NULL REFERENCES public.workspaces (id) ON DELETE CASCADE,
  owner_id uuid,
  name text NOT NULL DEFAULT '',
  company_id uuid REFERENCES public.companies (id) ON DELETE SET NULL,
  deleted_at timestamptz
);
CREATE TABLE public.contact_groups (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  workspace_id uuid NOT NULL REFERENCES public.workspaces (id) ON DELETE CASCADE,
  owner_id uuid NOT NULL,
  name text NOT NULL DEFAULT '',
  deleted_at timestamptz
);
CREATE TABLE public.contact_group_members (
  group_id uuid NOT NULL REFERENCES public.contact_groups (id) ON DELETE CASCADE,
  contact_id uuid NOT NULL REFERENCES public.contacts (id) ON DELETE CASCADE,
  PRIMARY KEY (group_id, contact_id)
);
CREATE TABLE public.contact_private_notes (
  contact_id uuid NOT NULL REFERENCES public.contacts (id) ON DELETE CASCADE,
  user_id uuid NOT NULL,
  body text NOT NULL DEFAULT '',
  PRIMARY KEY (contact_id, user_id)
);

CREATE TABLE public.calendar_accounts (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  workspace_id uuid NOT NULL REFERENCES public.workspaces (id) ON DELETE CASCADE,
  owner_id uuid,
  deleted_at timestamptz
);
CREATE TABLE public.calendars (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  workspace_id uuid NOT NULL REFERENCES public.workspaces (id) ON DELETE CASCADE,
  owner_id uuid NOT NULL,
  name text NOT NULL DEFAULT '',
  kind text NOT NULL DEFAULT 'moduo',
  account_id uuid REFERENCES public.calendar_accounts (id) ON DELETE CASCADE,
  deleted_at timestamptz
);
CREATE TABLE public.calendar_sets (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  workspace_id uuid NOT NULL REFERENCES public.workspaces (id) ON DELETE CASCADE,
  owner_id uuid NOT NULL,
  name text NOT NULL DEFAULT ''
);
CREATE TABLE public.calendar_set_items (
  set_id uuid NOT NULL REFERENCES public.calendar_sets (id) ON DELETE CASCADE,
  calendar_id uuid NOT NULL REFERENCES public.calendars (id) ON DELETE CASCADE,
  PRIMARY KEY (set_id, calendar_id)
);
CREATE TABLE public.calendar_events (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  workspace_id uuid REFERENCES public.workspaces (id) ON DELETE CASCADE,
  owner_id uuid NOT NULL REFERENCES public.profiles (id) ON DELETE CASCADE,
  title text NOT NULL DEFAULT '',
  calendar_ref uuid REFERENCES public.calendars (id) ON DELETE SET NULL,
  source_account_id uuid REFERENCES public.calendar_accounts (id) ON DELETE SET NULL,
  deleted_at timestamptz
);

CREATE TABLE public.email_accounts (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  workspace_id uuid NOT NULL REFERENCES public.workspaces (id) ON DELETE CASCADE,
  owner_id uuid NOT NULL,
  address text NOT NULL DEFAULT '',
  deleted_at timestamptz
);
CREATE TABLE public.email_refs (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  workspace_id uuid NOT NULL REFERENCES public.workspaces (id) ON DELETE CASCADE,
  owner_id uuid NOT NULL,
  account_id uuid REFERENCES public.email_accounts (id) ON DELETE SET NULL,
  subject text NOT NULL DEFAULT '',
  deleted_at timestamptz
);

CREATE TABLE public.chat_channels (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  workspace_id uuid NOT NULL REFERENCES public.workspaces (id) ON DELETE CASCADE,
  kind text NOT NULL CHECK (kind IN ('channel', 'dm')),
  name text,
  is_private boolean NOT NULL DEFAULT false,
  dm_key text,
  created_by uuid REFERENCES auth.users (id) ON DELETE SET NULL,
  managers_only boolean NOT NULL DEFAULT false
);
CREATE TABLE public.chat_members (
  channel_id uuid NOT NULL REFERENCES public.chat_channels (id) ON DELETE CASCADE,
  user_id uuid NOT NULL REFERENCES auth.users (id) ON DELETE CASCADE,
  workspace_id uuid NOT NULL,
  joined_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (channel_id, user_id)
);
CREATE TABLE public.chat_channel_managers (
  channel_id uuid NOT NULL REFERENCES public.chat_channels (id) ON DELETE CASCADE,
  user_id uuid NOT NULL,
  PRIMARY KEY (channel_id, user_id)
);
CREATE TABLE public.chat_messages (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  workspace_id uuid NOT NULL,
  channel_id uuid NOT NULL REFERENCES public.chat_channels (id) ON DELETE CASCADE,
  parent_id uuid REFERENCES public.chat_messages (id) ON DELETE CASCADE,
  author_id uuid REFERENCES auth.users (id) ON DELETE SET NULL,
  body text NOT NULL DEFAULT '',
  deleted_at timestamptz
);

CREATE TABLE public.resource_grants (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  workspace_id uuid NOT NULL REFERENCES public.workspaces (id) ON DELETE CASCADE,
  resource_type text NOT NULL,
  resource_id uuid NOT NULL,
  subject_type text NOT NULL CHECK (subject_type IN ('member', 'workspace', 'public_link')),
  subject_id uuid,
  level text NOT NULL CHECK (level IN ('freebusy', 'view', 'edit', 'full')),
  created_by uuid,
  created_at timestamptz NOT NULL DEFAULT now(),
  subject_key uuid GENERATED ALWAYS AS (coalesce(subject_id, '00000000-0000-0000-0000-000000000000'::uuid)) STORED,
  UNIQUE (resource_type, resource_id, subject_type, subject_key)
);

CREATE TABLE public.entities (
  workspace_id uuid NOT NULL REFERENCES public.workspaces (id) ON DELETE CASCADE,
  entity_type text NOT NULL,
  entity_id uuid NOT NULL,
  label text NOT NULL DEFAULT '',
  icon text,
  deleted_at timestamptz,
  PRIMARY KEY (workspace_id, entity_type, entity_id)
);
CREATE TABLE public.entity_links (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  workspace_id uuid NOT NULL,
  source_type text NOT NULL,
  source_id uuid NOT NULL,
  target_type text NOT NULL,
  target_id uuid NOT NULL,
  relation_kind text NOT NULL DEFAULT 'references',
  origin text NOT NULL DEFAULT 'manual',
  created_by uuid NOT NULL DEFAULT auth.uid(),
  created_at timestamptz NOT NULL DEFAULT now(),
  deleted_at timestamptz,
  FOREIGN KEY (workspace_id, source_type, source_id)
    REFERENCES public.entities (workspace_id, entity_type, entity_id) ON DELETE CASCADE,
  FOREIGN KEY (workspace_id, target_type, target_id)
    REFERENCES public.entities (workspace_id, entity_type, entity_id) ON DELETE CASCADE
);
CREATE TABLE public.comments (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  workspace_id uuid NOT NULL,
  entity_type text NOT NULL,
  entity_id uuid NOT NULL,
  body text NOT NULL DEFAULT '',
  created_by uuid NOT NULL DEFAULT auth.uid(),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  deleted_at timestamptz,
  author_kind text NOT NULL DEFAULT 'user',
  author_label text,
  FOREIGN KEY (workspace_id, entity_type, entity_id)
    REFERENCES public.entities (workspace_id, entity_type, entity_id) ON DELETE CASCADE
);
CREATE TABLE public.tag_links (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  workspace_id uuid NOT NULL,
  tag_id uuid NOT NULL,
  entity_type text NOT NULL,
  entity_id uuid NOT NULL
);
CREATE TABLE public.link_suggestion_declines (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  workspace_id uuid NOT NULL,
  pair_key text NOT NULL,
  declined_by uuid
);
CREATE TABLE public.module_activity (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  workspace_id uuid NOT NULL REFERENCES public.workspaces (id) ON DELETE CASCADE,
  module text NOT NULL DEFAULT 'x',
  entity_type text NOT NULL,
  entity_id uuid NOT NULL,
  op text NOT NULL DEFAULT 'x',
  actor_type text NOT NULL DEFAULT 'user',
  actor_id uuid,
  actor_label text,
  payload jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE TABLE public.notification_state (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  workspace_id uuid NOT NULL,
  user_id uuid NOT NULL,
  activity_id uuid NOT NULL REFERENCES public.module_activity (id) ON DELETE CASCADE,
  read_at timestamptz,
  dismissed_at timestamptz
);
CREATE TABLE public.workspace_api_keys (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  workspace_id uuid NOT NULL REFERENCES public.workspaces (id) ON DELETE CASCADE,
  name text NOT NULL DEFAULT '',
  created_by uuid,
  scopes jsonb NOT NULL DEFAULT '{}'::jsonb,
  revoked_at timestamptz
);
CREATE TABLE public.slot_bookings (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  slot_id text NOT NULL DEFAULT '',
  contact_id uuid,
  calendar_event_id uuid
);

-- ── Functions (production bodies) ───────────────────────────────────────────

CREATE FUNCTION public.module_api_key_id()
 RETURNS uuid
 LANGUAGE plpgsql
 STABLE
 SET search_path TO 'public'
AS $function$
DECLARE
  v uuid;
BEGIN
  IF coalesce(current_setting('request.jwt.claims', true)::jsonb ->> 'role', '')
     <> 'service_role' THEN
    RETURN NULL;
  END IF;
  BEGIN
    v := nullif(current_setting('request.headers', true)::jsonb ->> 'x-moduo-key-id', '')::uuid;
  EXCEPTION WHEN others THEN
    RETURN NULL;
  END;
  RETURN v;
END;
$function$
;

CREATE FUNCTION public.module_api_key_creator()
 RETURNS uuid
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  SELECT k.created_by
  FROM public.workspace_api_keys k
  WHERE k.id = public.module_api_key_id() AND k.revoked_at IS NULL
$function$
;

CREATE FUNCTION public.perm_actor_id()
 RETURNS uuid
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  SELECT coalesce(auth.uid(), public.module_api_key_creator())
$function$
;

CREATE FUNCTION public.grant_level_rank(p_level text)
 RETURNS integer
 LANGUAGE sql
 IMMUTABLE
AS $function$
  SELECT CASE p_level
    WHEN 'freebusy' THEN 1 WHEN 'view' THEN 2 WHEN 'edit' THEN 3 WHEN 'full' THEN 4
    ELSE 0 END
$function$
;

CREATE FUNCTION public.perm_rank(p_level text)
 RETURNS integer
 LANGUAGE sql
 IMMUTABLE
 SET search_path TO 'public'
AS $function$
  SELECT CASE p_level WHEN 'admin' THEN 3 WHEN 'edit' THEN 2 WHEN 'view' THEN 1 ELSE 0 END
$function$
;

CREATE FUNCTION public.perm_is_owner(p_workspace_id uuid, p_user_id uuid)
 RETURNS boolean
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  SELECT p_user_id IS NOT NULL AND EXISTS (
    SELECT 1 FROM public.workspaces w
    WHERE w.id = p_workspace_id AND w.owner_id = p_user_id AND w.deleted_at IS NULL)
$function$
;

CREATE FUNCTION public.perm_user_has(p_workspace_id uuid, p_user_id uuid, p_key text)
 RETURNS boolean
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  SELECT p_user_id IS NOT NULL AND (
    public.perm_is_owner(p_workspace_id, p_user_id)
    OR EXISTS (SELECT 1 FROM public.workspace_members m
               WHERE m.workspace_id = p_workspace_id AND m.user_id = p_user_id
                 AND p_key = ANY (m.perms)))
$function$
;

CREATE FUNCTION public.perm_ceiling_rank(p_workspace_id uuid, p_user_id uuid, p_module text)
 RETURNS integer
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  SELECT CASE
    WHEN p_user_id IS NULL THEN 0
    WHEN NOT public.perm_user_has(p_workspace_id, p_user_id, p_module || '.view') THEN 0
    WHEN public.perm_user_has(p_workspace_id, p_user_id, p_module || '.delete') THEN 4
    WHEN public.perm_user_has(p_workspace_id, p_user_id, p_module || '.edit') THEN 3
    ELSE 2
  END
$function$
;

CREATE FUNCTION public.share_direct_rank(p_type text, p_id uuid, p_user uuid)
 RETURNS integer
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  SELECT coalesce(max(public.grant_level_rank(g.level)), 0)
  FROM public.resource_grants g
  WHERE g.resource_type = p_type AND g.resource_id = p_id
    AND (
      (g.subject_type = 'member' AND g.subject_id = p_user)
      OR g.subject_type = 'workspace'
    )
$function$
;

CREATE FUNCTION public.can_access(p_type text, p_id uuid, p_min text, p_user uuid DEFAULT NULL::uuid)
 RETURNS boolean
 LANGUAGE plpgsql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
DECLARE
  v_user uuid := coalesce(p_user, public.perm_actor_id());
  v_need int := public.grant_level_rank(p_min);
  v_rank int := 0;
  v_ws uuid;
  v_module text;
  v_id uuid;
  v_parent uuid;
  v_mode text;
  v_creator uuid;
  v_system boolean;
  v_bucket uuid;
  v_cal uuid;
  v_guard int := 0;
BEGIN
  IF v_user IS NULL OR p_id IS NULL OR v_need = 0 THEN
    RETURN false;
  END IF;

  IF p_type = 'note' THEN
    v_id := p_id;
    LOOP
      v_guard := v_guard + 1;
      EXIT WHEN v_guard > 100;
      SELECT workspace_id, parent_id, coalesce(share_mode, 'custom'), created_by
        INTO v_ws, v_parent, v_mode, v_creator
      FROM public.notes WHERE id = v_id;
      EXIT WHEN NOT FOUND;
      IF v_creator = v_user THEN v_rank := greatest(v_rank, 4); END IF;
      v_rank := greatest(v_rank, public.share_direct_rank('note', v_id, v_user));
      EXIT WHEN v_mode IS DISTINCT FROM 'inherit' OR v_parent IS NULL;
      v_id := v_parent;
    END LOOP;
    v_module := 'notes';

  ELSIF p_type = 'bucket' THEN
    SELECT workspace_id, owner_id, is_system INTO v_ws, v_creator, v_system
    FROM public.buckets WHERE id = p_id;
    IF NOT FOUND THEN RETURN false; END IF;
    IF v_system THEN
      v_rank := CASE WHEN v_creator = v_user THEN 4 ELSE 0 END;
    ELSE
      IF v_creator = v_user THEN v_rank := 4; END IF;
      v_rank := greatest(v_rank, public.share_direct_rank('bucket', p_id, v_user));
    END IF;
    v_module := 'tasks';

  ELSIF p_type = 'task' THEN
    SELECT workspace_id, bucket_id INTO v_ws, v_bucket FROM public.tasks WHERE id = p_id;
    IF NOT FOUND THEN RETURN false; END IF;
    v_rank := public.share_direct_rank('task', p_id, v_user);
    IF v_bucket IS NOT NULL THEN
      -- Inherit the bucket. Call the rank by re-entering for 'full' then scaling
      -- is wrong; read the bucket rank directly via a nested check's grant.
      IF public.can_access('bucket', v_bucket, 'full', v_user) THEN v_rank := greatest(v_rank, 4);
      ELSIF public.can_access('bucket', v_bucket, 'edit', v_user) THEN v_rank := greatest(v_rank, 3);
      ELSIF public.can_access('bucket', v_bucket, 'view', v_user) THEN v_rank := greatest(v_rank, 2);
      END IF;
    END IF;
    v_module := 'tasks';

  ELSIF p_type = 'calendar' THEN
    SELECT workspace_id, owner_id INTO v_ws, v_creator FROM public.calendars WHERE id = p_id AND deleted_at IS NULL;
    IF NOT FOUND THEN RETURN false; END IF;
    IF v_creator = v_user THEN v_rank := 4; END IF;
    v_rank := greatest(v_rank, public.share_direct_rank('calendar', p_id, v_user));
    v_module := 'calendar';

  ELSIF p_type = 'contact_group' THEN
    SELECT workspace_id, owner_id INTO v_ws, v_creator
    FROM public.contact_groups WHERE id = p_id AND deleted_at IS NULL;
    IF NOT FOUND THEN RETURN false; END IF;
    IF v_creator = v_user THEN v_rank := 4; END IF;
    v_rank := greatest(v_rank, public.share_direct_rank('contact_group', p_id, v_user));
    v_module := 'contacts';

  ELSIF p_type = 'contact' THEN
    SELECT workspace_id, owner_id INTO v_ws, v_creator
    FROM public.contacts WHERE id = p_id AND deleted_at IS NULL;
    IF NOT FOUND THEN RETURN false; END IF;
    IF v_creator = v_user THEN v_rank := 4; END IF;
    v_rank := greatest(v_rank, public.share_direct_rank('contact', p_id, v_user));
    IF EXISTS (
      SELECT 1 FROM public.contact_group_members gm
      JOIN public.contact_groups g ON g.id = gm.group_id AND g.deleted_at IS NULL
      WHERE gm.contact_id = p_id AND public.can_access('contact_group', g.id, 'view', v_user)
    ) THEN
      v_rank := greatest(v_rank, 2);
    END IF;
    IF EXISTS (
      SELECT 1 FROM public.contact_group_members gm
      JOIN public.contact_groups g ON g.id = gm.group_id AND g.deleted_at IS NULL
      WHERE gm.contact_id = p_id AND public.can_access('contact_group', g.id, 'edit', v_user)
    ) THEN
      v_rank := greatest(v_rank, 3);
    END IF;
    v_module := 'contacts';

  ELSIF p_type = 'company' THEN
    SELECT workspace_id, owner_id INTO v_ws, v_creator
    FROM public.companies WHERE id = p_id AND deleted_at IS NULL;
    IF NOT FOUND THEN RETURN false; END IF;
    IF v_creator = v_user THEN v_rank := 4; END IF;
    IF EXISTS (
      SELECT 1 FROM public.contacts c
      WHERE c.company_id = p_id AND c.deleted_at IS NULL
        AND public.can_access('contact', c.id, 'view', v_user)
    ) THEN
      v_rank := greatest(v_rank, 2);
    END IF;
    v_module := 'contacts';

  ELSIF p_type = 'event' THEN
    SELECT workspace_id, owner_id, calendar_ref INTO v_ws, v_creator, v_cal
    FROM public.calendar_events WHERE id = p_id AND deleted_at IS NULL;
    IF NOT FOUND THEN RETURN false; END IF;
    IF v_creator = v_user THEN
      v_rank := 4;
      v_module := 'calendar';
    ELSIF v_cal IS NOT NULL THEN
      RETURN public.can_access('calendar', v_cal, p_min, v_user);
    ELSE
      RETURN false;
    END IF;

  ELSE
    RETURN false;
  END IF;

  IF v_ws IS NULL THEN RETURN false; END IF;
  RETURN least(v_rank, public.perm_ceiling_rank(v_ws, v_user, v_module)) >= v_need;
END;
$function$
;

CREATE FUNCTION public.module_member_permission(p_workspace_id uuid, p_user_id uuid, p_lane text)
 RETURNS text
 LANGUAGE plpgsql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
DECLARE
  m public.workspace_members;
  v_mods text[];
BEGIN
  IF p_user_id IS NULL THEN RETURN 'none'; END IF;
  IF public.perm_is_owner(p_workspace_id, p_user_id) THEN RETURN 'admin'; END IF;
  SELECT * INTO m FROM public.workspace_members
   WHERE workspace_id = p_workspace_id AND user_id = p_user_id LIMIT 1;
  IF m.id IS NULL THEN RETURN 'none'; END IF;

  IF p_lane = 'email' THEN
    IF m.role = 'viewer' THEN RETURN 'view'; END IF;
    RETURN CASE lower(coalesce(m.permissions_email, 'edit'))
      WHEN 'none' THEN 'none' WHEN 'read' THEN 'view' WHEN 'view' THEN 'view' ELSE 'edit' END;
  END IF;

  v_mods := CASE WHEN p_lane = 'spine' THEN ARRAY['notes','tasks','calendar','contacts','chat']
                 ELSE ARRAY[p_lane] END;
  IF EXISTS (SELECT 1 FROM unnest(m.perms) k
             WHERE split_part(k, '.', 1) = ANY (v_mods)
               AND split_part(k, '.', 2) IN ('create', 'edit', 'delete')) THEN
    RETURN 'edit';
  END IF;
  IF EXISTS (SELECT 1 FROM unnest(m.perms) k
             WHERE split_part(k, '.', 1) = ANY (v_mods) AND split_part(k, '.', 2) = 'view') THEN
    RETURN 'view';
  END IF;
  RETURN 'none';
END;
$function$
;

CREATE FUNCTION public.module_api_key_scope(p_workspace_id uuid, p_scope_key text, p_lane text)
 RETURNS text
 LANGUAGE plpgsql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
DECLARE
  v_key_scope text;
  v_creator   uuid;
  v_member    text;
BEGIN
  SELECT CASE lower(coalesce(k.scopes ->> p_scope_key, 'none'))
           WHEN 'edit' THEN 'edit'
           WHEN 'view' THEN 'view'
           ELSE 'none'
         END,
         k.created_by
    INTO v_key_scope, v_creator
    FROM public.workspace_api_keys k
   WHERE k.id = public.module_api_key_id()
     AND k.workspace_id = p_workspace_id
     AND k.revoked_at IS NULL;

  IF v_key_scope IS NULL OR v_creator IS NULL THEN
    RETURN 'none';
  END IF;

  v_member := public.module_member_permission(p_workspace_id, v_creator, p_lane);
  IF public.perm_rank(v_member) < public.perm_rank(v_key_scope) THEN
    RETURN CASE WHEN v_member = 'view' THEN 'view' ELSE 'none' END;
  END IF;
  RETURN v_key_scope;
END;
$function$
;

CREATE FUNCTION public.tasks_module_permission(p_workspace_id uuid)
 RETURNS text
 LANGUAGE plpgsql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
BEGIN
  IF public.module_api_key_id() IS NOT NULL THEN
    RETURN public.module_api_key_scope(p_workspace_id, 'tasks', 'tasks');
  END IF;
  RETURN public.module_member_permission(p_workspace_id, auth.uid(), 'tasks');
END;
$function$
;

CREATE FUNCTION public.spine_module_permission(p_workspace_id uuid)
 RETURNS text
 LANGUAGE plpgsql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
BEGIN
  IF public.module_api_key_id() IS NOT NULL THEN
    RETURN public.module_api_key_scope(p_workspace_id, 'links', 'spine');
  END IF;
  RETURN public.module_member_permission(p_workspace_id, auth.uid(), 'spine');
END;
$function$
;

CREATE FUNCTION public.tasks_module_can_access_workspace(p_workspace_id uuid)
 RETURNS boolean
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  SELECT EXISTS (
    SELECT 1 FROM public.workspaces w
    WHERE w.id = p_workspace_id
      AND w.owner_id = auth.uid()
      AND w.deleted_at IS NULL
  ) OR EXISTS (
    SELECT 1 FROM public.workspace_members m
    WHERE m.workspace_id = p_workspace_id
      AND m.user_id = auth.uid()
  );
$function$
;

CREATE FUNCTION public.spine_pair_key(a_type text, a_id uuid, b_type text, b_id uuid)
 RETURNS text
 LANGUAGE sql
 IMMUTABLE
AS $function$
  SELECT CASE
    WHEN (a_type || ':' || a_id::text) COLLATE "C"
       <= (b_type || ':' || b_id::text) COLLATE "C"
    THEN (a_type || ':' || a_id::text) || '|' || (b_type || ':' || b_id::text)
    ELSE (b_type || ':' || b_id::text) || '|' || (a_type || ':' || a_id::text)
  END;
$function$
;

CREATE FUNCTION public.module_activity_log(p_workspace_id uuid, p_module text, p_entity_type text, p_entity_id uuid, p_op text, p_payload jsonb)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
DECLARE
  v_key uuid;
  v_label text;
BEGIN
  IF auth.uid() IS NOT NULL THEN
    INSERT INTO public.module_activity
      (workspace_id, module, entity_type, entity_id, op,
       actor_type, actor_id, actor_label, payload)
    VALUES (
      p_workspace_id, p_module, p_entity_type, p_entity_id, p_op,
      'user', auth.uid(),
      (SELECT p.display_name FROM public.profiles p WHERE p.id = auth.uid()),
      coalesce(p_payload, '{}'::jsonb)
    );
    RETURN;
  END IF;
  v_key := public.module_api_key_id();
  IF v_key IS NULL THEN
    RAISE EXCEPTION 'No actor context for activity attribution.';
  END IF;
  SELECT k.name INTO v_label FROM public.workspace_api_keys k WHERE k.id = v_key;
  INSERT INTO public.module_activity
    (workspace_id, module, entity_type, entity_id, op,
     actor_type, actor_id, actor_label, payload)
  VALUES (
    p_workspace_id, p_module, p_entity_type, p_entity_id, p_op,
    'api_key', v_key, v_label, coalesce(p_payload, '{}'::jsonb)
  );
END;
$function$
;

CREATE FUNCTION public.entities_op_ensure(p_workspace_id uuid, p_entity_type text, p_entity_id uuid, p_label text DEFAULT NULL::text, p_icon text DEFAULT NULL::text)
 RETURNS void
 LANGUAGE sql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  INSERT INTO public.entities (workspace_id, entity_type, entity_id, label, icon)
  VALUES (p_workspace_id, p_entity_type, p_entity_id, coalesce(p_label, ''), p_icon)
  ON CONFLICT (workspace_id, entity_type, entity_id) DO NOTHING;
$function$
;

CREATE FUNCTION public.spine_op__guard(p_workspace_id uuid)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
BEGIN
  IF public.spine_module_permission(p_workspace_id) NOT IN ('edit', 'admin') THEN
    RAISE EXCEPTION 'You don''t have edit access to links in this workspace.';
  END IF;
END;
$function$
;

CREATE FUNCTION public.comments_op_add(p_workspace_id uuid, p_entity_type text, p_entity_id uuid, p_body text, p_mentioned_user_ids uuid[] DEFAULT '{}'::uuid[], p_entity_label text DEFAULT NULL::text, p_entity_icon text DEFAULT NULL::text)
 RETURNS comments
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
DECLARE
  v_comment public.comments;
  v_body text := coalesce(p_body, '');
  v_mentions jsonb := to_jsonb(coalesce(p_mentioned_user_ids, '{}'::uuid[]));
  v_owner uuid;
  v_notify jsonb;
  v_key uuid := public.module_api_key_id();
  v_key_label text;
BEGIN
  PERFORM public.spine_op__guard(p_workspace_id);
  IF trim(v_body) = '' THEN
    RAISE EXCEPTION 'A comment can''t be empty.';
  END IF;

  -- Ensure the target exists in the registry (satisfies the FK) without
  -- reviving a tombstone or clobbering an authoritative label.
  PERFORM public.entities_op_ensure(p_workspace_id, p_entity_type, p_entity_id, p_entity_label, p_entity_icon);

  -- A key's comment belongs to its creator (created_by is NOT NULL, and the
  -- creator's access governs it) but reads as the app that wrote it.
  IF v_key IS NOT NULL THEN
    SELECT k.name INTO v_key_label FROM public.workspace_api_keys k WHERE k.id = v_key;
  END IF;
  INSERT INTO public.comments
    (workspace_id, entity_type, entity_id, body, created_by, author_kind, author_label)
  VALUES (
    p_workspace_id, p_entity_type, p_entity_id, v_body, public.perm_actor_id(),
    CASE WHEN v_key IS NULL THEN 'user' ELSE 'api_key' END,
    CASE WHEN v_key IS NULL THEN NULL ELSE coalesce(v_key_label, 'App') END)
  RETURNING * INTO v_comment;

  -- Resolve the entity owner for the types that have one. Owner-less entities
  -- (contact/company/event) leave v_owner NULL → only participants notify. A
  -- soft-deleted (trashed) task/note resolves to NULL too — don't ping an owner
  -- about a comment on something in their trash.
  IF p_entity_type = 'task' THEN
    SELECT t.owner_id INTO v_owner FROM public.tasks t
      WHERE t.id = p_entity_id AND t.workspace_id = p_workspace_id AND t.deleted_at IS NULL;
  ELSIF p_entity_type = 'note' THEN
    SELECT n.created_by INTO v_owner FROM public.notes n
      WHERE n.id = p_entity_id AND n.workspace_id = p_workspace_id AND n.deleted_at IS NULL;
  END IF;

  -- notify_user_ids = (owner ∪ prior participants) − the actor. De-duped; TEXT
  -- ids to match the predicate's `@> jsonb_build_array(auth.uid()::text)`.
  -- New here: a key's comment reads as the app, not as its creator, so it
  -- notifies the creator like anyone else's comment would (Maciej, 2026-10-08).
  SELECT coalesce(jsonb_agg(DISTINCT s.uid::text), '[]'::jsonb) INTO v_notify
  FROM (
    SELECT c.created_by AS uid
    FROM public.comments c
    WHERE c.workspace_id = p_workspace_id
      AND c.entity_type = p_entity_type
      AND c.entity_id = p_entity_id
      AND c.deleted_at IS NULL
    UNION
    SELECT v_owner
    WHERE v_owner IS NOT NULL
  ) s
  WHERE v_key IS NOT NULL OR s.uid IS DISTINCT FROM public.perm_actor_id();

  PERFORM public.module_activity_log(
    p_workspace_id, 'comments', p_entity_type, p_entity_id, 'comments.add',
    jsonb_build_object(
      'comment_id', v_comment.id,
      -- A short excerpt for the notification card — never the full body.
      'excerpt', left(v_body, 140),
      'mentioned_user_ids', v_mentions,
      'notify_user_ids', v_notify)
  );
  RETURN v_comment;
END;
$function$
;

CREATE FUNCTION public.spine_activity_targets_me(p_activity module_activity)
 RETURNS boolean
 LANGUAGE sql
 STABLE
 SET search_path TO 'public'
AS $function$
  SELECT (
      -- Someone else named me (comment @mention). Not my own action.
      p_activity.actor_id IS DISTINCT FROM auth.uid()
      AND (p_activity.payload -> 'mentioned_user_ids') @> jsonb_build_array(auth.uid()::text)
    ) OR (
      -- A self-notification (snooze-due / follow-up-due): I set it for myself, so I
      -- AM the actor — the actor≠me guard must NOT apply here.
      (p_activity.payload -> 'notify_user_ids') @> jsonb_build_array(auth.uid()::text)
    );
$function$
;

CREATE FUNCTION public.notifications_list(p_workspace_id uuid, p_limit integer DEFAULT 50)
 RETURNS TABLE(id uuid, workspace_id uuid, module text, entity_type text, entity_id uuid, op text, actor_type text, actor_id uuid, actor_label text, payload jsonb, created_at timestamp with time zone, read_at timestamp with time zone, dismissed_at timestamp with time zone)
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  SELECT ma.id, ma.workspace_id, ma.module, ma.entity_type, ma.entity_id, ma.op,
         ma.actor_type, ma.actor_id, ma.actor_label, ma.payload, ma.created_at,
         ns.read_at, ns.dismissed_at
  FROM public.module_activity ma
  LEFT JOIN public.notification_state ns
    ON ns.activity_id = ma.id AND ns.user_id = auth.uid()
  WHERE ma.workspace_id = p_workspace_id
    AND public.tasks_module_can_access_workspace(p_workspace_id)
    AND public.spine_activity_targets_me(ma)
  ORDER BY ma.created_at DESC
  LIMIT coalesce(p_limit, 50);
$function$
;

CREATE FUNCTION public.tasks_op__guard(p_workspace_id uuid, p_task_id uuid)
 RETURNS tasks
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
DECLARE
  t public.tasks;
BEGIN
  IF public.tasks_module_permission(p_workspace_id) NOT IN ('edit', 'admin') THEN
    RAISE EXCEPTION 'You don''t have edit access to Tasks in this workspace.';
  END IF;
  SELECT * INTO t FROM public.tasks
    WHERE id = p_task_id AND workspace_id = p_workspace_id AND deleted_at IS NULL
    FOR UPDATE;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'Task not found in this workspace.';
  END IF;
  RETURN t;
END;
$function$
;

CREATE FUNCTION public.tasks_op_set_status(p_workspace_id uuid, p_task_id uuid, p_status text, p_recurrence jsonb DEFAULT NULL::jsonb, p_position text DEFAULT NULL::text)
 RETURNS tasks
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
DECLARE
  t public.tasks;
  v_from text;
BEGIN
  t := public.tasks_op__guard(p_workspace_id, p_task_id);
  IF p_status IS NULL OR p_status NOT IN ('todo', 'in_progress', 'done', 'archived') THEN
    RAISE EXCEPTION 'Unknown task status.';
  END IF;
  IF t.status = p_status AND p_position IS NULL AND p_recurrence IS NULL THEN
    RETURN t; -- no-op
  END IF;
  v_from := t.status;
  UPDATE public.tasks
    SET status = p_status,
        recurrence = CASE WHEN p_recurrence IS NOT NULL AND t.recurrence IS NOT NULL
                          THEN p_recurrence ELSE recurrence END,
        position = coalesce(p_position, position),
        updated_at = now()
    WHERE id = t.id
    RETURNING * INTO t;
  IF v_from <> t.status THEN
    PERFORM public.module_activity_log(
      p_workspace_id, 'tasks', 'task', t.id, 'tasks.set_status',
      jsonb_build_object('from', v_from, 'to', t.status,
                         'next_occurrence', p_recurrence ->> 'nextOccurrence')
    );
  END IF;
  RETURN t;
END;
$function$
;

CREATE FUNCTION public.share_member_count(p_workspace_id uuid)
 RETURNS integer
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  SELECT count(*)::int FROM public.workspace_members m WHERE m.workspace_id = p_workspace_id
$function$
;

CREATE FUNCTION public.share_grant_workspace(p_workspace_id uuid, p_type text, p_id uuid, p_level text)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
BEGIN
  IF p_level IS NULL OR p_level = 'private' THEN RETURN; END IF;
  IF public.share_member_count(p_workspace_id) < 2 THEN RETURN; END IF;
  INSERT INTO public.resource_grants (workspace_id, resource_type, resource_id, subject_type, level, created_by)
  VALUES (p_workspace_id, p_type, p_id, 'workspace', p_level, public.perm_actor_id())
  ON CONFLICT (resource_type, resource_id, subject_type, subject_key)
  DO UPDATE SET level = EXCLUDED.level;
END;
$function$
;

CREATE FUNCTION public.share_assign_preview(p_bucket_id uuid, p_user_id uuid)
 RETURNS text
 LANGUAGE plpgsql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
DECLARE
  v_name text;
  v_person text;
BEGIN
  IF public.can_access('bucket', p_bucket_id, 'view', p_user_id) THEN RETURN NULL; END IF;
  SELECT name INTO v_name FROM public.buckets WHERE id = p_bucket_id;
  SELECT coalesce(nullif(display_name, ''), 'They') INTO v_person FROM public.profiles WHERE id = p_user_id;
  RETURN coalesce(v_person, 'They') || ' can''t see "' || coalesce(v_name, 'this bucket') || '" — they''ll only see this task.';
END;
$function$
;

CREATE FUNCTION public.account_erasure_rank(p_type text, p_id uuid, p_user uuid)
 RETURNS integer
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  SELECT CASE
    WHEN public.can_access(p_type, p_id, 'full', p_user) THEN 4
    WHEN public.can_access(p_type, p_id, 'edit', p_user) THEN 3
    WHEN public.can_access(p_type, p_id, 'view', p_user) THEN 2
    ELSE 0
  END
$function$
;

CREATE FUNCTION public.account_erasure_new_owner(p_type text, p_id uuid, p_workspace_id uuid, p_user uuid)
 RETURNS uuid
 LANGUAGE plpgsql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
DECLARE
  v_owner uuid;
  v_pick uuid;
BEGIN
  SELECT w.owner_id INTO v_owner FROM public.workspaces w WHERE w.id = p_workspace_id;
  IF v_owner IS NOT NULL AND v_owner <> p_user
     AND public.can_access(p_type, p_id, 'view', v_owner) THEN
    RETURN v_owner;
  END IF;

  SELECT m.user_id INTO v_pick
  FROM public.workspace_members m
  WHERE m.workspace_id = p_workspace_id
    AND m.user_id <> p_user
    AND public.can_access(p_type, p_id, 'view', m.user_id)
  ORDER BY public.account_erasure_rank(p_type, p_id, m.user_id) DESC,
           (SELECT min(g.created_at) FROM public.resource_grants g
             WHERE g.resource_type = p_type AND g.resource_id = p_id
               AND g.subject_type = 'member' AND g.subject_id = m.user_id) ASC NULLS LAST,
           m.joined_at ASC,
           m.user_id
  LIMIT 1;
  RETURN v_pick;
END;
$function$
;

CREATE FUNCTION public.account_erasure_inbox(p_workspace_id uuid, p_user uuid)
 RETURNS uuid
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
DECLARE
  v_id uuid;
BEGIN
  SELECT b.id INTO v_id
  FROM public.buckets b
  WHERE b.workspace_id = p_workspace_id AND b.owner_id = p_user
    AND b.is_system AND b.deleted_at IS NULL
  LIMIT 1;
  IF v_id IS NOT NULL THEN
    RETURN v_id;
  END IF;
  INSERT INTO public.buckets (workspace_id, owner_id, name, is_system, position, created_at, updated_at)
  VALUES (p_workspace_id, p_user, 'Inbox', true, 'a0', now(), now())
  RETURNING id INTO v_id;
  RETURN v_id;
END;
$function$
;

CREATE FUNCTION public.account_erase_workspace_data(p_user uuid, p_preview boolean DEFAULT true)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
DECLARE
  v_owned uuid[];
  r record;
  v_new uuid;
  v_owner uuid;
  i integer;

  v_note_del uuid[] := '{}';     v_note_keep uuid[] := '{}';     v_note_to uuid[] := '{}';
  v_bucket_del uuid[] := '{}';   v_bucket_keep uuid[] := '{}';   v_bucket_to uuid[] := '{}';
  v_task_del uuid[] := '{}';     v_task_move uuid[] := '{}';     v_task_move_to uuid[] := '{}';
  v_contact_del uuid[] := '{}';  v_contact_keep uuid[] := '{}';  v_contact_to uuid[] := '{}';
  v_group_del uuid[] := '{}';    v_group_keep uuid[] := '{}';    v_group_to uuid[] := '{}';
  v_company_del uuid[] := '{}';  v_company_keep uuid[] := '{}';  v_company_to uuid[] := '{}';
  v_event_del uuid[];
  v_calendar_del uuid[];
  v_set_del uuid[];
  v_account_del uuid[];
  v_email_ref_del uuid[];
  v_email_account_del uuid[];
  v_channel_del uuid[];
  v_manager_channel uuid[] := '{}';
  v_manager_to uuid[] := '{}';
  v_task_unassign integer;
  v_notification_state integer;
  v_api_keys integer;
  v_member_grants integer;
  v_email text;
  v_invites integer;
  v_bypass text;

  v_keys text[];        -- 'type:id' of every deleted item
  v_id_texts text[];    -- every deleted id, for activity payloads (target_id)
  v_counts jsonb;
BEGIN
  IF p_user IS NULL THEN
    RAISE EXCEPTION 'account_erase_workspace_data: p_user is required';
  END IF;

  -- Workspaces the user owns are left to the auth cascade.
  SELECT coalesce(array_agg(w.id), '{}') INTO v_owned
  FROM public.workspaces w WHERE w.owner_id = p_user;

  -- ── Decide, before anything changes (every decision reads today's access) ──

  FOR r IN
    SELECT n.id, n.workspace_id FROM public.notes n
    WHERE n.created_by = p_user AND n.workspace_id <> ALL (v_owned)
  LOOP
    v_new := public.account_erasure_new_owner('note', r.id, r.workspace_id, p_user);
    IF v_new IS NULL THEN
      v_note_del := v_note_del || r.id;
    ELSE
      v_note_keep := v_note_keep || r.id;
      v_note_to := v_note_to || v_new;
    END IF;
  END LOOP;

  -- The Inbox is only ever its owner's, so it always goes.
  FOR r IN
    SELECT b.id, b.workspace_id FROM public.buckets b
    WHERE b.owner_id = p_user AND b.workspace_id <> ALL (v_owned)
  LOOP
    v_new := public.account_erasure_new_owner('bucket', r.id, r.workspace_id, p_user);
    IF v_new IS NULL THEN
      v_bucket_del := v_bucket_del || r.id;
    ELSE
      v_bucket_keep := v_bucket_keep || r.id;
      v_bucket_to := v_bucket_to || v_new;
    END IF;
  END LOOP;

  -- tasks.bucket_id is RESTRICT: every task in a bucket that goes either moves
  -- (someone else can see it, e.g. an assignee's grant) or goes too.
  FOR r IN
    SELECT t.id, t.workspace_id, t.owner_id FROM public.tasks t WHERE t.bucket_id = ANY (v_bucket_del)
  LOOP
    IF NOT EXISTS (SELECT 1 FROM public.resource_grants g
                   WHERE g.resource_type = 'task' AND g.resource_id = r.id) THEN
      -- can_access gives a task its own grants plus its bucket's access, and
      -- nobody else can see this bucket: without a grant the task is private.
      -- (A shortcut, so a big private bucket doesn't cost a search per task.)
      v_new := NULL;
    ELSIF r.owner_id IS NOT NULL AND r.owner_id <> p_user
          AND public.can_access('task', r.id, 'view', r.owner_id) THEN
      -- The teammate it's assigned to keeps it, in their own Inbox.
      v_new := r.owner_id;
    ELSE
      v_new := public.account_erasure_new_owner('task', r.id, r.workspace_id, p_user);
    END IF;
    IF v_new IS NULL THEN
      v_task_del := v_task_del || r.id;
    ELSE
      v_task_move := v_task_move || r.id;
      v_task_move_to := v_task_move_to || v_new;
    END IF;
  END LOOP;

  FOR r IN
    SELECT c.id, c.workspace_id FROM public.contacts c
    WHERE c.owner_id = p_user AND c.workspace_id <> ALL (v_owned)
  LOOP
    v_new := public.account_erasure_new_owner('contact', r.id, r.workspace_id, p_user);
    IF v_new IS NULL THEN
      v_contact_del := v_contact_del || r.id;
    ELSE
      v_contact_keep := v_contact_keep || r.id;
      v_contact_to := v_contact_to || v_new;
    END IF;
  END LOOP;

  FOR r IN
    SELECT g.id, g.workspace_id FROM public.contact_groups g
    WHERE g.owner_id = p_user AND g.workspace_id <> ALL (v_owned)
  LOOP
    v_new := public.account_erasure_new_owner('contact_group', r.id, r.workspace_id, p_user);
    IF v_new IS NULL THEN
      v_group_del := v_group_del || r.id;
    ELSE
      v_group_keep := v_group_keep || r.id;
      v_group_to := v_group_to || v_new;
    END IF;
  END LOOP;

  -- A company is visible through any contact the viewer can see that points at
  -- it. Contacts that go are private, so they never made a company visible.
  FOR r IN
    SELECT co.id, co.workspace_id FROM public.companies co
    WHERE co.owner_id = p_user AND co.workspace_id <> ALL (v_owned)
  LOOP
    v_new := public.account_erasure_new_owner('company', r.id, r.workspace_id, p_user);
    IF v_new IS NULL THEN
      v_company_del := v_company_del || r.id;
    ELSE
      v_company_keep := v_company_keep || r.id;
      v_company_to := v_company_to || v_new;
    END IF;
  END LOOP;

  -- Every event is filed in its owner's own calendar, so the user's calendars
  -- would only keep an empty name (integration calendars are often named after
  -- an email address). All of it goes.
  SELECT coalesce(array_agg(e.id), '{}') INTO v_event_del
  FROM public.calendar_events e
  WHERE e.owner_id = p_user AND e.workspace_id <> ALL (v_owned);

  SELECT coalesce(array_agg(c.id), '{}') INTO v_calendar_del
  FROM public.calendars c WHERE c.owner_id = p_user AND c.workspace_id <> ALL (v_owned);

  SELECT coalesce(array_agg(s.id), '{}') INTO v_set_del
  FROM public.calendar_sets s WHERE s.owner_id = p_user AND s.workspace_id <> ALL (v_owned);

  SELECT coalesce(array_agg(a.id), '{}') INTO v_account_del
  FROM public.calendar_accounts a WHERE a.owner_id = p_user AND a.workspace_id <> ALL (v_owned);

  -- Email has no sharing: everything is the owner's alone.
  SELECT coalesce(array_agg(x.id), '{}') INTO v_email_ref_del
  FROM public.email_refs x WHERE x.owner_id = p_user AND x.workspace_id <> ALL (v_owned);

  SELECT coalesce(array_agg(x.id), '{}') INTO v_email_account_del
  FROM public.email_accounts x WHERE x.owner_id = p_user AND x.workspace_id <> ALL (v_owned);

  -- Chat rows outlive membership (someone who leaves keeps their chat_members
  -- and manager rows but can't open the workspace), so only people still in the
  -- workspace count below.
  -- A DM or private channel with nobody else still here in it, e.g. their DM
  -- with themselves.
  SELECT coalesce(array_agg(c.id), '{}') INTO v_channel_del
  FROM public.chat_channels c
  WHERE c.workspace_id <> ALL (v_owned)
    AND (c.kind = 'dm' OR c.is_private)
    AND EXISTS (SELECT 1 FROM public.chat_members cm
                WHERE cm.channel_id = c.id AND cm.user_id = p_user)
    AND NOT EXISTS (
      SELECT 1 FROM public.chat_members cm
      WHERE cm.channel_id = c.id AND cm.user_id <> p_user
        AND (EXISTS (SELECT 1 FROM public.workspace_members wm
                     WHERE wm.workspace_id = c.workspace_id AND wm.user_id = cm.user_id)
             OR EXISTS (SELECT 1 FROM public.workspaces w
                        WHERE w.id = c.workspace_id AND w.owner_id = cm.user_id)));

  -- Channels the user managed alone: the workspace owner if they can see the
  -- channel, otherwise the earliest member still here.
  FOR r IN
    SELECT c.id, c.workspace_id, c.is_private
    FROM public.chat_channel_managers m
    JOIN public.chat_channels c ON c.id = m.channel_id
    WHERE m.user_id = p_user
      AND c.workspace_id <> ALL (v_owned)
      AND NOT (c.id = ANY (v_channel_del))
      AND NOT EXISTS (
        SELECT 1 FROM public.chat_channel_managers m2
        WHERE m2.channel_id = c.id AND m2.user_id <> p_user
          AND (EXISTS (SELECT 1 FROM public.workspace_members wm
                       WHERE wm.workspace_id = c.workspace_id AND wm.user_id = m2.user_id)
               OR EXISTS (SELECT 1 FROM public.workspaces w
                          WHERE w.id = c.workspace_id AND w.owner_id = m2.user_id)))
  LOOP
    v_new := NULL;
    SELECT w.owner_id INTO v_owner FROM public.workspaces w WHERE w.id = r.workspace_id;
    IF v_owner IS NOT NULL AND v_owner <> p_user
       AND (NOT r.is_private OR EXISTS (SELECT 1 FROM public.chat_members cm
                                        WHERE cm.channel_id = r.id AND cm.user_id = v_owner)) THEN
      v_new := v_owner;
    ELSE
      SELECT cm.user_id INTO v_new
      FROM public.chat_members cm
      JOIN public.workspace_members wm ON wm.workspace_id = r.workspace_id AND wm.user_id = cm.user_id
      WHERE cm.channel_id = r.id AND cm.user_id <> p_user
      ORDER BY cm.joined_at, cm.user_id
      LIMIT 1;
      IF v_new IS NULL AND NOT r.is_private THEN
        SELECT m.user_id INTO v_new
        FROM public.workspace_members m
        WHERE m.workspace_id = r.workspace_id AND m.user_id <> p_user
        ORDER BY m.joined_at, m.user_id
        LIMIT 1;
      END IF;
    END IF;
    IF v_new IS NOT NULL THEN
      v_manager_channel := v_manager_channel || r.id;
      v_manager_to := v_manager_to || v_new;
    END IF;
  END LOOP;

  SELECT count(*) INTO v_task_unassign
  FROM public.tasks t
  WHERE t.owner_id = p_user AND t.workspace_id <> ALL (v_owned)
    AND NOT (t.id = ANY (v_task_del));

  SELECT count(*) INTO v_notification_state
  FROM public.notification_state s WHERE s.user_id = p_user;

  SELECT count(*) INTO v_api_keys
  FROM public.workspace_api_keys k
  WHERE k.created_by = p_user AND k.workspace_id <> ALL (v_owned);

  SELECT count(*) INTO v_member_grants
  FROM public.resource_grants g
  WHERE g.subject_type = 'member' AND g.subject_id = p_user;

  -- Invitations they accepted keep their email address; they have no use once
  -- the person is in (pending ones are the inviter's and stay).
  SELECT u.email INTO v_email FROM auth.users u WHERE u.id = p_user;
  SELECT count(*) INTO v_invites
  FROM public.workspace_invites i
  WHERE i.workspace_id <> ALL (v_owned) AND i.status = 'accepted'
    AND lower(i.email) = lower(v_email);

  v_counts := jsonb_build_object(
    'preview', p_preview IS NOT FALSE,
    'notes_deleted', cardinality(v_note_del),
    'notes_handed_over', cardinality(v_note_keep),
    'buckets_deleted', cardinality(v_bucket_del),
    'buckets_handed_over', cardinality(v_bucket_keep),
    'tasks_deleted', cardinality(v_task_del),
    'tasks_moved', cardinality(v_task_move),
    'tasks_unassigned', v_task_unassign,
    'contacts_deleted', cardinality(v_contact_del),
    'contacts_handed_over', cardinality(v_contact_keep),
    'contact_groups_deleted', cardinality(v_group_del),
    'contact_groups_handed_over', cardinality(v_group_keep),
    'companies_deleted', cardinality(v_company_del),
    'companies_handed_over', cardinality(v_company_keep),
    'events_deleted', cardinality(v_event_del),
    'calendars_deleted', cardinality(v_calendar_del),
    'calendar_sets_deleted', cardinality(v_set_del),
    'calendar_accounts_deleted', cardinality(v_account_del),
    'email_refs_deleted', cardinality(v_email_ref_del),
    'email_accounts_deleted', cardinality(v_email_account_del),
    'chat_channels_deleted', cardinality(v_channel_del),
    'chat_managers_handed_over', cardinality(v_manager_channel),
    'notification_state_deleted', v_notification_state,
    'api_keys_deleted', v_api_keys,
    'member_grants_deleted', v_member_grants,
    'invites_deleted', v_invites
  );

  -- Only an explicit false deletes; NULL previews like the default.
  IF p_preview IS NOT FALSE THEN
    RETURN v_counts;
  END IF;

  -- ── Apply ──────────────────────────────────────────────────────────────────

  -- Restored before returning, so a caller's later statements aren't bypassed.
  v_bypass := current_setting('share.bypass', true);
  PERFORM set_config('share.bypass', '1', true);

  -- 1. Shared items get their new owner.
  UPDATE public.notes n SET created_by = x.to_user
  FROM unnest(v_note_keep, v_note_to) AS x(id, to_user) WHERE n.id = x.id;
  UPDATE public.buckets b SET owner_id = x.to_user
  FROM unnest(v_bucket_keep, v_bucket_to) AS x(id, to_user) WHERE b.id = x.id;
  UPDATE public.contacts c SET owner_id = x.to_user
  FROM unnest(v_contact_keep, v_contact_to) AS x(id, to_user) WHERE c.id = x.id;
  UPDATE public.contact_groups g SET owner_id = x.to_user
  FROM unnest(v_group_keep, v_group_to) AS x(id, to_user) WHERE g.id = x.id;
  UPDATE public.companies co SET owner_id = x.to_user
  FROM unnest(v_company_keep, v_company_to) AS x(id, to_user) WHERE co.id = x.id;

  -- 2. Shared tasks leave the buckets that go, into their new owner's Inbox.
  FOR i IN 1 .. cardinality(v_task_move) LOOP
    UPDATE public.tasks t
    SET bucket_id = public.account_erasure_inbox(t.workspace_id, v_task_move_to[i])
    WHERE t.id = v_task_move[i];
  END LOOP;

  -- 3. Tasks assigned to the user are unassigned (the moved ones included).
  UPDATE public.tasks t SET owner_id = NULL
  WHERE t.owner_id = p_user AND t.workspace_id <> ALL (v_owned)
    AND NOT (t.id = ANY (v_task_del));

  -- 4. Chat: new managers first, then the user's manager rows, then channels
  --    with nobody else in them (members and messages cascade).
  INSERT INTO public.chat_channel_managers (channel_id, user_id)
  SELECT x.channel_id, x.user_id FROM unnest(v_manager_channel, v_manager_to) AS x(channel_id, user_id)
  ON CONFLICT DO NOTHING;
  DELETE FROM public.chat_channel_managers m
  USING public.chat_channels c
  WHERE c.id = m.channel_id AND m.user_id = p_user AND c.workspace_id <> ALL (v_owned);
  DELETE FROM public.chat_channels c WHERE c.id = ANY (v_channel_del);

  -- 5. What points at the deleted items without a foreign key, addressed as
  --    'type:id' in every type the spine (perm_can_see_entity), activity and
  --    grants use for them.
  SELECT coalesce(array_agg(k), '{}') INTO v_keys FROM (
    SELECT 'note:' || x AS k FROM unnest(v_note_del) AS x
    UNION ALL SELECT 'bucket:' || x FROM unnest(v_bucket_del) AS x
    UNION ALL SELECT 'task:' || x FROM unnest(v_task_del) AS x
    UNION ALL SELECT 'task_project:' || x FROM unnest(v_task_del) AS x
    UNION ALL SELECT 'contact:' || x FROM unnest(v_contact_del) AS x
    UNION ALL SELECT 'contact_group:' || x FROM unnest(v_group_del) AS x
    UNION ALL SELECT 'company:' || x FROM unnest(v_company_del) AS x
    UNION ALL SELECT 'event:' || x FROM unnest(v_event_del) AS x
    UNION ALL SELECT 'calendar:' || x FROM unnest(v_calendar_del) AS x
    UNION ALL SELECT 'calendar_set:' || x FROM unnest(v_set_del) AS x
    UNION ALL SELECT 'calendar_account:' || x FROM unnest(v_account_del) AS x
    UNION ALL SELECT 'email_thread:' || x FROM unnest(v_email_ref_del) AS x
    UNION ALL SELECT 'email_account:' || x FROM unnest(v_email_account_del) AS x
    UNION ALL SELECT 'chat_channel:' || x FROM unnest(v_channel_del) AS x
  ) s;

  SELECT coalesce(array_agg(split_part(k, ':', 2)), '{}') INTO v_id_texts
  FROM unnest(v_keys) AS k;

  -- Activity rows (notification state cascades), including links-module rows
  -- whose deleted item is only the payload's target.
  DELETE FROM public.module_activity a
  WHERE (a.entity_type || ':' || a.entity_id) = ANY (v_keys)
     OR (a.payload ->> 'target_id') = ANY (v_id_texts);
  -- Activity only the user could read (RLS shows calendar and email activity to
  -- the actor and the item's owner), also for items removed earlier. A calendar
  -- account's entries carry its label, often an email address.
  DELETE FROM public.module_activity a
  WHERE a.workspace_id <> ALL (v_owned)
    AND a.actor_type = 'user' AND a.actor_id = p_user
    AND (a.entity_type IN ('calendar_account', 'email_account', 'email_thread')
         OR (a.entity_type = 'event' AND NOT EXISTS (
               SELECT 1 FROM public.calendar_events e
               WHERE e.id = a.entity_id AND e.owner_id <> p_user)));
  -- The rest of their activity stays, without their name: module_activity_log
  -- copies the actor's display name into actor_label, and the app shows it.
  UPDATE public.module_activity a SET actor_label = NULL
  WHERE a.workspace_id <> ALL (v_owned)
    AND a.actor_type = 'user' AND a.actor_id = p_user AND a.actor_label IS NOT NULL;
  DELETE FROM public.tag_links tl
  WHERE (tl.entity_type || ':' || tl.entity_id) = ANY (v_keys);
  DELETE FROM public.link_suggestion_declines d
  WHERE split_part(d.pair_key, '|', 1) = ANY (v_keys)
     OR split_part(d.pair_key, '|', 2) = ANY (v_keys);
  -- Entities: their links (either end) and every comment on them cascade.
  DELETE FROM public.entities e
  WHERE (e.entity_type || ':' || e.entity_id) = ANY (v_keys);

  -- 6. The items. Children before parents where a foreign key restricts.
  DELETE FROM public.exposed_notes x WHERE x.note_id = ANY (v_note_del::text[]);
  -- note_shares has a foreign key whose delete rule no migration records.
  DELETE FROM public.note_shares s WHERE s.note_id = ANY (v_note_del);
  -- notes.parent_id is SET NULL: a teammate's sub-note under a deleted note
  -- moves to the top level. note_updates cascade.
  DELETE FROM public.notes n WHERE n.id = ANY (v_note_del);

  UPDATE public.slot_bookings b SET contact_id = NULL WHERE b.contact_id = ANY (v_contact_del);
  UPDATE public.slot_bookings b SET calendar_event_id = NULL WHERE b.calendar_event_id = ANY (v_event_del);

  DELETE FROM public.tasks t WHERE t.id = ANY (v_task_del);
  DELETE FROM public.buckets b WHERE b.id = ANY (v_bucket_del);
  -- Time blocks map a slot to a bucket id; drop the slots of buckets that went.
  UPDATE public.task_time_blocks tb
  SET blocks = coalesce((
        SELECT jsonb_object_agg(j.key, j.value)
        FROM jsonb_each(tb.blocks) AS j
        WHERE NOT coalesce((j.value #>> '{}') = ANY (v_bucket_del::text[]), false)
      ), '{}'::jsonb),
      updated_at = now()
  WHERE EXISTS (SELECT 1 FROM jsonb_each(tb.blocks) AS j
                WHERE (j.value #>> '{}') = ANY (v_bucket_del::text[]));

  -- Group memberships and private notes on contacts cascade; contacts.company_id
  -- is SET NULL.
  DELETE FROM public.contact_groups g WHERE g.id = ANY (v_group_del);
  DELETE FROM public.contacts c WHERE c.id = ANY (v_contact_del);
  DELETE FROM public.companies co WHERE co.id = ANY (v_company_del);

  -- Events before accounts: calendar_events.source_account_id is SET NULL.
  -- Set items cascade; deleting an account also deletes its calendar.
  DELETE FROM public.calendar_events e WHERE e.id = ANY (v_event_del);
  DELETE FROM public.calendar_sets s WHERE s.id = ANY (v_set_del);
  DELETE FROM public.calendars c WHERE c.id = ANY (v_calendar_del);
  DELETE FROM public.calendar_accounts a WHERE a.id = ANY (v_account_del);

  -- email_refs.account_id is SET NULL, so refs go first.
  DELETE FROM public.email_refs x WHERE x.id = ANY (v_email_ref_del);
  DELETE FROM public.email_accounts x WHERE x.id = ANY (v_email_account_del);

  -- 7. Grants on everything that went, every grant to the user, their read
  --    state, the API keys they created (keys stop working without a creator
  --    anyway) and the invitations they accepted.
  DELETE FROM public.resource_grants g
  WHERE (g.resource_type || ':' || g.resource_id) = ANY (v_keys)
     OR (g.subject_type = 'member' AND g.subject_id = p_user);
  DELETE FROM public.notification_state s WHERE s.user_id = p_user;
  DELETE FROM public.workspace_api_keys k
  WHERE k.created_by = p_user AND k.workspace_id <> ALL (v_owned);
  DELETE FROM public.workspace_invites i
  WHERE i.workspace_id <> ALL (v_owned) AND i.status = 'accepted'
    AND lower(i.email) = lower(v_email);

  PERFORM set_config('share.bypass', coalesce(v_bypass, ''), true);
  RETURN v_counts;
END;
$function$
;

CREATE FUNCTION public.perm_enforce_write()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
DECLARE
  v_module text := TG_ARGV[0];
  v_fixed  text := CASE WHEN TG_NARGS > 1 THEN TG_ARGV[1] ELSE NULL END;
  v_ws     uuid;
  v_actor  uuid;
  v_action text;
  v_verb   text;
  v_need   text;
  v_item   text;   -- 'edit' requirement for items inside a container
BEGIN
  v_ws := CASE WHEN TG_OP = 'DELETE' THEN OLD.workspace_id ELSE NEW.workspace_id END;
  v_actor := public.perm_actor_id();

  -- Member-removal archive writes notes the actor can't open. The removal
  -- function sets this for the rest of its transaction only.
  IF current_setting('share.bypass', true) = '1' THEN
    RETURN coalesce(NEW, OLD);
  END IF;

  -- System work (service role without a key, cron, migrations).
  IF v_actor IS NULL OR v_ws IS NULL THEN
    RETURN coalesce(NEW, OLD);
  END IF;

  IF v_fixed IS NOT NULL THEN
    v_action := v_fixed;
  ELSIF TG_OP = 'INSERT' THEN
    v_action := 'create';
  ELSIF TG_OP = 'DELETE' THEN
    v_action := 'delete';
  ELSE
    v_action := 'edit';
  END IF;

  -- Mirrored external calendar events are the owner's own sync, not edits.
  IF TG_TABLE_NAME = 'calendar_events' THEN
    IF (CASE WHEN TG_OP = 'DELETE' THEN OLD.source_account_id ELSE NEW.source_account_id END) IS NOT NULL THEN
      RETURN coalesce(NEW, OLD);
    END IF;
  END IF;

  -- The first channel of a workspace is chat's own bootstrap (#general).
  IF TG_TABLE_NAME = 'chat_channels' THEN
    IF NOT EXISTS (SELECT 1 FROM public.chat_channels c
                   WHERE c.workspace_id = v_ws AND c.id IS DISTINCT FROM coalesce(NEW.id, OLD.id)) THEN
      RETURN coalesce(NEW, OLD);
    END IF;
  END IF;

  -- Soft delete / restore count as delete. Only tables guarded without a
  -- fixed action, all of which have deleted_at (chat_channels is INSERT-only).
  IF TG_OP = 'UPDATE' AND v_fixed IS NULL AND TG_TABLE_NAME <> 'chat_channels' THEN
    IF NEW.deleted_at IS DISTINCT FROM OLD.deleted_at THEN
      v_action := 'delete';
    ELSIF TG_TABLE_NAME = 'chat_messages' THEN
      -- Reactions / thread counters live on the message row; only a body
      -- change is an edit.
      IF NEW.body IS NOT DISTINCT FROM OLD.body THEN
        RETURN NEW;
      END IF;
    END IF;
  END IF;

  IF NOT public.perm_is_owner(v_ws, v_actor)
     AND NOT public.perm_user_has(v_ws, v_actor, v_module || '.' || v_action) THEN
    v_verb := CASE v_action WHEN 'create' THEN 'add' ELSE v_action END;
    RAISE EXCEPTION 'Your role can''t % % in this workspace.', v_verb,
      CASE v_module WHEN 'tasks' THEN 'tasks' WHEN 'notes' THEN 'notes' WHEN 'calendar' THEN 'events'
                    WHEN 'contacts' THEN 'contacts' WHEN 'chat' THEN 'messages' ELSE v_module END
      USING ERRCODE = '42501';
  END IF;

  v_need := CASE WHEN v_action = 'delete' THEN 'full' ELSE 'edit' END;
  v_item := 'edit';

  IF TG_TABLE_NAME = 'notes' THEN
    IF TG_OP = 'UPDATE' THEN
      IF OLD.publish_token IS NULL AND NEW.publish_token IS NOT NULL
         AND NOT public.perm_user_has(v_ws, v_actor, 'ws.publish') THEN
        RAISE EXCEPTION 'Your role can''t publish to the web in this workspace.' USING ERRCODE = '42501';
      END IF;
    END IF;
    IF TG_OP = 'INSERT' THEN
      IF NEW.parent_id IS NOT NULL AND NOT public.can_access('note', NEW.parent_id, 'edit', v_actor) THEN
        RAISE EXCEPTION 'You don''t have access to this note.' USING ERRCODE = '42501';
      END IF;
    ELSIF NOT public.can_access('note', OLD.id, v_need, v_actor) THEN
      RAISE EXCEPTION 'You don''t have access to this note.' USING ERRCODE = '42501';
    END IF;

  ELSIF TG_TABLE_NAME = 'note_updates' THEN
    IF NOT public.can_access('note', coalesce(NEW.note_id, OLD.note_id), 'edit', v_actor) THEN
      RAISE EXCEPTION 'You don''t have access to this note.' USING ERRCODE = '42501';
    END IF;

  ELSIF TG_TABLE_NAME = 'buckets' THEN
    IF TG_OP <> 'INSERT' AND NOT public.can_access('bucket', OLD.id, v_need, v_actor) THEN
      RAISE EXCEPTION 'You don''t have access to this bucket.' USING ERRCODE = '42501';
    END IF;

  ELSIF TG_TABLE_NAME = 'tasks' THEN
    IF TG_OP = 'INSERT' THEN
      IF NOT public.can_access('bucket', NEW.bucket_id, 'edit', v_actor) THEN
        RAISE EXCEPTION 'You don''t have access to this bucket.' USING ERRCODE = '42501';
      END IF;
    ELSE
      -- Tasks are items inside a bucket: Edit covers deleting them.
      IF NOT public.can_access('task', OLD.id, v_item, v_actor) THEN
        RAISE EXCEPTION 'You don''t have access to this task.' USING ERRCODE = '42501';
      END IF;
      -- Moving a task into another bucket needs Edit there too.
      IF TG_OP = 'UPDATE' AND NEW.bucket_id IS DISTINCT FROM OLD.bucket_id
         AND NOT public.can_access('bucket', NEW.bucket_id, 'edit', v_actor) THEN
        RAISE EXCEPTION 'You don''t have access to this bucket.' USING ERRCODE = '42501';
      END IF;
    END IF;
    IF TG_OP <> 'DELETE' AND NEW.owner_id IS NOT NULL
       AND NOT public.perm_user_has(v_ws, NEW.owner_id, 'tasks.edit') THEN
      RAISE EXCEPTION 'Viewers can''t be assigned tasks.' USING ERRCODE = '42501';
    END IF;

  ELSIF TG_TABLE_NAME = 'contacts' THEN
    IF TG_OP <> 'INSERT' AND NOT public.can_access('contact', OLD.id, v_need, v_actor) THEN
      RAISE EXCEPTION 'You don''t have access to this contact.' USING ERRCODE = '42501';
    END IF;

  ELSIF TG_TABLE_NAME = 'companies' THEN
    IF TG_OP <> 'INSERT' AND NOT public.can_access('company', OLD.id, 'edit', v_actor) THEN
      RAISE EXCEPTION 'You don''t have access to this company.' USING ERRCODE = '42501';
    END IF;

  ELSIF TG_TABLE_NAME = 'calendar_events' THEN
    -- Events are items inside a calendar: Edit covers deleting them.
    IF TG_OP <> 'INSERT' THEN
      IF OLD.owner_id IS DISTINCT FROM v_actor
         AND (OLD.calendar_ref IS NULL OR NOT public.can_access('calendar', OLD.calendar_ref, v_item, v_actor)) THEN
        RAISE EXCEPTION 'You don''t have access to this event.' USING ERRCODE = '42501';
      END IF;
    END IF;

  ELSIF TG_TABLE_NAME = 'chat_messages' THEN
    IF v_action = 'delete' AND TG_OP <> 'INSERT' THEN
      IF OLD.author_id IS DISTINCT FROM v_actor
         AND NOT public.chat_has_cap(v_ws, v_actor, 'delete_others') THEN
        RAISE EXCEPTION 'Your role can''t delete other people''s messages.' USING ERRCODE = '42501';
      END IF;
    END IF;
  END IF;

  RETURN coalesce(NEW, OLD);
END;
$function$
;

CREATE FUNCTION public.notes_share_fields_owner_only()
 RETURNS trigger
 LANGUAGE plpgsql
 SET search_path TO 'public'
AS $function$
BEGIN
  IF current_setting('share.bypass', true) = '1' THEN
    RETURN NEW;
  END IF;

  IF TG_OP = 'UPDATE'
    AND auth.uid() IS NOT NULL
    AND OLD.created_by IS DISTINCT FROM auth.uid()
    AND (
      OLD.share_scope IS DISTINCT FROM NEW.share_scope
      OR OLD.share_permission IS DISTINCT FROM NEW.share_permission
      OR OLD.created_by IS DISTINCT FROM NEW.created_by
      OR OLD.workspace_id IS DISTINCT FROM NEW.workspace_id
    )
  THEN
    RAISE EXCEPTION 'only the note owner can change sharing or ownership';
  END IF;

  RETURN NEW;
END;
$function$
;

CREATE FUNCTION public.share_task_assign()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
BEGIN
  IF NEW.owner_id IS NULL THEN RETURN NEW; END IF;
  IF TG_OP = 'UPDATE' AND NEW.owner_id IS NOT DISTINCT FROM OLD.owner_id THEN RETURN NEW; END IF;
  IF public.can_access('bucket', NEW.bucket_id, 'edit', NEW.owner_id) THEN RETURN NEW; END IF;
  INSERT INTO public.resource_grants (workspace_id, resource_type, resource_id, subject_type, subject_id, level, created_by)
  VALUES (NEW.workspace_id, 'task', NEW.id, 'member', NEW.owner_id, 'edit', public.perm_actor_id())
  ON CONFLICT (resource_type, resource_id, subject_type, subject_key)
  DO UPDATE SET level = 'edit';
  RETURN NEW;
END;
$function$
;

CREATE FUNCTION public.tasks_notify_spine()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
DECLARE
  v_blocked RECORD;
BEGIN
  -- Never notify about a soft-deleted row (a delete is an UPDATE that stamps
  -- deleted_at; it must not read as an assignment or an unblock).
  IF NEW.deleted_at IS NOT NULL THEN
    RETURN NULL;
  END IF;

  -- ── assigned-to-you ──────────────────────────────────────────────────────────
  -- A task whose owner is a member OTHER than the actor performing the write:
  -- a create-on-someone's-behalf (INSERT) or a re-assignment (UPDATE where owner
  -- changed). mentioned_user_ids + the actor≠me predicate keep self-owned tasks
  -- silent. Wrapped so a notification failure can never fail the task write.
  IF (TG_OP = 'INSERT'
        AND NEW.owner_id IS NOT NULL
        AND NEW.owner_id IS DISTINCT FROM auth.uid())
     OR (TG_OP = 'UPDATE'
        AND NEW.owner_id IS NOT NULL
        AND NEW.owner_id IS DISTINCT FROM OLD.owner_id
        AND NEW.owner_id IS DISTINCT FROM auth.uid()) THEN
    BEGIN
      PERFORM public.module_activity_log(
        NEW.workspace_id, 'tasks', 'task', NEW.id, 'tasks.assigned',
        jsonb_build_object(
          'mentioned_user_ids', jsonb_build_array(NEW.owner_id::text),
          'title', NEW.title));
    EXCEPTION WHEN OTHERS THEN
      -- generation is a side-effect; it must never break completing/editing a task.
      -- Surface a WARNING (does not abort the txn) so a silent failure is debuggable.
      RAISE WARNING 'tasks_notify_spine: assigned notification failed for task %: %', NEW.id, SQLERRM;
    END;
  END IF;

  -- ── blocked-task-unblocked ───────────────────────────────────────────────────
  -- This task just CLOSED (open → done/archived). For every task it blocked, if
  -- this was its LAST open blocker, notify that task's owner. "Open" mirrors the
  -- client isOpen set (status NOT IN done/archived). Only fires for a genuine
  -- open→closed transition, so re-saving an already-done task can't re-notify.
  IF TG_OP = 'UPDATE'
     AND OLD.status NOT IN ('done', 'archived')
     AND NEW.status IN ('done', 'archived') THEN
    BEGIN
      FOR v_blocked IN
        SELECT bt.id AS task_id, bt.owner_id AS owner_id, bt.title AS title
        FROM public.task_relations r
        JOIN public.tasks bt ON bt.id = r.blocked_task_id
        WHERE r.blocker_task_id = NEW.id
          AND r.workspace_id = NEW.workspace_id
          AND bt.deleted_at IS NULL
          AND bt.owner_id IS NOT NULL
          -- Only nudge if the freed task is still actionable (not already closed).
          AND bt.status NOT IN ('done', 'archived')
          -- …and no OTHER open blocker remains on it.
          AND NOT EXISTS (
            SELECT 1
            FROM public.task_relations r2
            JOIN public.tasks ob ON ob.id = r2.blocker_task_id
            WHERE r2.blocked_task_id = r.blocked_task_id
              AND r2.blocker_task_id <> NEW.id
              AND ob.deleted_at IS NULL
              AND ob.status NOT IN ('done', 'archived')
          )
      LOOP
        PERFORM public.module_activity_log(
          NEW.workspace_id, 'tasks', 'task', v_blocked.task_id, 'tasks.unblocked',
          jsonb_build_object(
            'notify_user_ids', jsonb_build_array(v_blocked.owner_id::text),
            'title', v_blocked.title,
            'blocker_title', NEW.title));
      END LOOP;
    EXCEPTION WHEN OTHERS THEN
      -- as above: never let the notification side-effect fail the task write.
      RAISE WARNING 'tasks_notify_spine: unblocked notification failed for blocker %: %', NEW.id, SQLERRM;
    END;
  END IF;

  RETURN NULL; -- AFTER trigger: return value is ignored
END;
$function$
;

CREATE FUNCTION public.share_bucket_after()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
DECLARE v_level text;
BEGIN
  IF NEW.is_system THEN RETURN NEW; END IF;
  SELECT buckets INTO v_level FROM public.workspace_share_defaults WHERE workspace_id = NEW.workspace_id;
  PERFORM public.share_grant_workspace(NEW.workspace_id, 'bucket', NEW.id, coalesce(v_level, 'edit'));
  RETURN NEW;
END;
$function$
;

CREATE FUNCTION public.share_sync_note_flag()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
DECLARE
  v_type text := CASE WHEN TG_OP = 'DELETE' THEN OLD.resource_type ELSE NEW.resource_type END;
  v_id uuid := CASE WHEN TG_OP = 'DELETE' THEN OLD.resource_id ELSE NEW.resource_id END;
BEGIN
  IF v_type = 'note' THEN
    UPDATE public.notes SET workspace_shared = EXISTS (
      SELECT 1 FROM public.resource_grants g
      WHERE g.resource_type = 'note' AND g.resource_id = v_id AND g.subject_type = 'workspace'
    ) WHERE id = v_id;
  END IF;
  RETURN coalesce(NEW, OLD);
END;
$function$
;

CREATE FUNCTION public.tasks_enforce_one_level_subtasks()
 RETURNS trigger
 LANGUAGE plpgsql
 SET search_path TO 'public'
AS $function$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM public.tasks p
    WHERE p.id = NEW.parent_id
      AND p.workspace_id = NEW.workspace_id
      AND p.parent_id IS NULL
  ) THEN
    RAISE EXCEPTION 'Subtasks are one level: the parent must be a top-level task in the same workspace';
  END IF;
  IF EXISTS (
    SELECT 1 FROM public.tasks c
    WHERE c.parent_id = NEW.id
      AND c.deleted_at IS NULL
  ) THEN
    RAISE EXCEPTION 'Subtasks are one level: a task with subtasks cannot become a subtask';
  END IF;
  RETURN NEW;
END;
$function$
;

CREATE FUNCTION public.tasks_relations_mirror_to_links()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
DECLARE
  v_actor uuid;
BEGIN
  IF TG_OP = 'INSERT' THEN
    v_actor := COALESCE(auth.uid(), (SELECT w.owner_id FROM public.workspaces w WHERE w.id = NEW.workspace_id));
    PERFORM public.entities_op_ensure(NEW.workspace_id, 'task', NEW.blocker_task_id,
      (SELECT t.title FROM public.tasks t WHERE t.id = NEW.blocker_task_id), 'task');
    PERFORM public.entities_op_ensure(NEW.workspace_id, 'task', NEW.blocked_task_id,
      (SELECT t.title FROM public.tasks t WHERE t.id = NEW.blocked_task_id), 'task');
    INSERT INTO public.entity_links
      (workspace_id, source_type, source_id, target_type, target_id, relation_kind, origin, created_by)
    VALUES
      (NEW.workspace_id, 'task', NEW.blocker_task_id, 'task', NEW.blocked_task_id, 'blocks', 'manual', v_actor)
    ON CONFLICT (workspace_id, pair_key, relation_kind) WHERE deleted_at IS NULL
    DO NOTHING;
    RETURN NEW;

  ELSIF TG_OP = 'DELETE' THEN
    UPDATE public.entity_links
      SET deleted_at = now()
      WHERE workspace_id = OLD.workspace_id
        AND relation_kind = 'blocks'
        AND deleted_at IS NULL
        AND pair_key = public.spine_pair_key('task', OLD.blocker_task_id, 'task', OLD.blocked_task_id);
    RETURN OLD;
  END IF;
  RETURN NULL;
END;
$function$
;

CREATE FUNCTION public.share_member_removed()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
DECLARE
  v_owner uuid;
  v_name text;
BEGIN
  SELECT owner_id INTO v_owner FROM public.workspaces WHERE id = OLD.workspace_id AND deleted_at IS NULL;
  IF v_owner IS NULL OR v_owner = OLD.user_id THEN RETURN OLD; END IF;
  PERFORM set_config('share.bypass', '1', true);

  -- A non-member can't own a task: perm_enforce_write refuses every later edit
  -- of it ("Viewers can't be assigned tasks"). Unassign instead.
  UPDATE public.tasks SET owner_id = NULL
  WHERE workspace_id = OLD.workspace_id AND owner_id = OLD.user_id;

  DELETE FROM public.resource_grants
  WHERE subject_type = 'member' AND subject_id = OLD.user_id AND workspace_id = OLD.workspace_id;

  -- Account deletion: this cascade runs after the profile is gone. Private
  -- items were erased before it (account_erase_workspace_data); whatever a
  -- deletion outside the app left behind must never reach the owner.
  IF NOT EXISTS (SELECT 1 FROM public.profiles WHERE id = OLD.user_id) THEN
    RETURN OLD;
  END IF;

  SELECT coalesce(nullif(btrim(display_name), ''), 'Member') INTO v_name
  FROM public.profiles WHERE id = OLD.user_id;
  v_name := coalesce(v_name, 'Member');

  UPDATE public.notes SET
    created_by = v_owner,
    title = 'From ' || v_name || ' (archived) ' || title
  WHERE workspace_id = OLD.workspace_id
    AND created_by = OLD.user_id
    AND deleted_at IS NULL
    AND share_mode = 'custom'
    AND NOT EXISTS (
      SELECT 1 FROM public.resource_grants g
      WHERE g.resource_type = 'note' AND g.resource_id = notes.id AND g.subject_type = 'workspace'
    );

  UPDATE public.buckets SET
    owner_id = v_owner,
    name = 'From ' || v_name || ' (archived) ' || name
  WHERE workspace_id = OLD.workspace_id
    AND owner_id = OLD.user_id
    AND deleted_at IS NULL
    AND is_system = false
    AND NOT EXISTS (
      SELECT 1 FROM public.resource_grants g
      WHERE g.resource_type = 'bucket' AND g.resource_id = buckets.id AND g.subject_type = 'workspace'
    );

  RETURN OLD;
END;
$function$
;

-- Stub: only chat_messages writes call it, and the probe makes none.
CREATE FUNCTION public.chat_has_cap(p_workspace_id uuid, p_user uuid, p_cap text) RETURNS boolean
LANGUAGE sql STABLE AS $$ SELECT false $$;

-- ── Triggers (production's) ──────────────────────────────────────────────────

CREATE TRIGGER perm_enforce_write BEFORE INSERT OR UPDATE OR DELETE ON public.notes
  FOR EACH ROW EXECUTE FUNCTION public.perm_enforce_write('notes');
CREATE TRIGGER notes_share_fields_owner_only BEFORE UPDATE ON public.notes
  FOR EACH ROW EXECUTE FUNCTION public.notes_share_fields_owner_only();
CREATE TRIGGER perm_enforce_write BEFORE INSERT OR UPDATE OR DELETE ON public.note_updates
  FOR EACH ROW EXECUTE FUNCTION public.perm_enforce_write('notes', 'edit');
CREATE TRIGGER perm_enforce_write BEFORE INSERT OR UPDATE OR DELETE ON public.buckets
  FOR EACH ROW EXECUTE FUNCTION public.perm_enforce_write('tasks');
CREATE TRIGGER share_bucket_after AFTER INSERT ON public.buckets
  FOR EACH ROW EXECUTE FUNCTION public.share_bucket_after();
CREATE TRIGGER perm_enforce_write BEFORE INSERT OR UPDATE OR DELETE ON public.tasks
  FOR EACH ROW EXECUTE FUNCTION public.perm_enforce_write('tasks');
CREATE TRIGGER share_task_assign AFTER INSERT OR UPDATE OF owner_id ON public.tasks
  FOR EACH ROW EXECUTE FUNCTION public.share_task_assign();
CREATE TRIGGER tasks_notify_spine AFTER INSERT OR UPDATE ON public.tasks
  FOR EACH ROW EXECUTE FUNCTION public.tasks_notify_spine();
CREATE TRIGGER tasks_one_level_subtasks BEFORE INSERT OR UPDATE OF parent_id ON public.tasks
  FOR EACH ROW WHEN (NEW.parent_id IS NOT NULL) EXECUTE FUNCTION public.tasks_enforce_one_level_subtasks();
CREATE TRIGGER perm_enforce_write BEFORE INSERT OR UPDATE OR DELETE ON public.task_relations
  FOR EACH ROW EXECUTE FUNCTION public.perm_enforce_write('tasks', 'edit');
CREATE TRIGGER tasks_relations_mirror_to_links AFTER INSERT OR DELETE ON public.task_relations
  FOR EACH ROW EXECUTE FUNCTION public.tasks_relations_mirror_to_links();
CREATE TRIGGER perm_enforce_write BEFORE INSERT OR UPDATE OR DELETE ON public.task_time_blocks
  FOR EACH ROW EXECUTE FUNCTION public.perm_enforce_write('tasks', 'edit');
CREATE TRIGGER perm_enforce_write BEFORE INSERT OR UPDATE OR DELETE ON public.contacts
  FOR EACH ROW EXECUTE FUNCTION public.perm_enforce_write('contacts');
CREATE TRIGGER perm_enforce_write BEFORE INSERT OR UPDATE OR DELETE ON public.companies
  FOR EACH ROW EXECUTE FUNCTION public.perm_enforce_write('contacts');
CREATE TRIGGER perm_enforce_write BEFORE INSERT OR UPDATE OR DELETE ON public.calendar_events
  FOR EACH ROW EXECUTE FUNCTION public.perm_enforce_write('calendar');
CREATE TRIGGER perm_enforce_write BEFORE INSERT ON public.chat_channels
  FOR EACH ROW EXECUTE FUNCTION public.perm_enforce_write('chat');
CREATE TRIGGER perm_enforce_write BEFORE INSERT OR UPDATE OR DELETE ON public.chat_messages
  FOR EACH ROW EXECUTE FUNCTION public.perm_enforce_write('chat');
CREATE TRIGGER share_sync_note_flag AFTER INSERT OR UPDATE OR DELETE ON public.resource_grants
  FOR EACH ROW EXECUTE FUNCTION public.share_sync_note_flag();
CREATE TRIGGER share_member_removed AFTER DELETE ON public.workspace_members
  FOR EACH ROW EXECUTE FUNCTION public.share_member_removed();

RESET check_function_bodies;

-- pair_key is generated from spine_pair_key, so it comes after the functions.
ALTER TABLE public.entity_links
  ADD COLUMN pair_key text GENERATED ALWAYS AS (public.spine_pair_key(source_type, source_id, target_type, target_id)) STORED;
CREATE UNIQUE INDEX entity_links_unique_pair_kind_idx
  ON public.entity_links (workspace_id, pair_key, relation_kind) WHERE deleted_at IS NULL;

-- ── Grants and RLS on tasks, as on production ───────────────────────────────
-- Supabase grants every role all table privileges; RLS does the gating.
GRANT USAGE ON SCHEMA public TO anon, authenticated, service_role;
GRANT USAGE ON SCHEMA auth TO anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION auth.uid() TO anon, authenticated, service_role;
GRANT ALL ON public.tasks TO anon, authenticated, service_role;
ALTER TABLE public.tasks ENABLE ROW LEVEL SECURITY;
CREATE POLICY tasks_workspace_access ON public.tasks FOR ALL TO authenticated
  USING (public.can_access('task', id, 'view') OR public.can_access('bucket', bucket_id, 'view'))
  WITH CHECK (public.can_access('task', id, 'view') OR public.can_access('bucket', bucket_id, 'edit'));

-- Production's revokes on the internal helpers (anon and authenticated can't
-- call them; definer functions still can).
DO $$
DECLARE fn text;
BEGIN
  FOREACH fn IN ARRAY ARRAY[
    'perm_actor_id()', 'module_api_key_creator()', 'module_activity_log(uuid, text, text, uuid, text, jsonb)',
    'tasks_op__guard(uuid, uuid)', 'perm_user_has(uuid, uuid, text)', 'perm_is_owner(uuid, uuid)',
    'entities_op_ensure(uuid, text, uuid, text, text)', 'module_api_key_scope(uuid, text, text)',
    'module_member_permission(uuid, uuid, text)', 'spine_op__guard(uuid)',
    'perm_enforce_write()', 'account_erase_workspace_data(uuid, boolean)'
  ] LOOP
    EXECUTE format('REVOKE ALL ON FUNCTION public.%s FROM PUBLIC, anon, authenticated', fn);
  END LOOP;
END;
$$;
