// The spine's activity-rendering vocabulary: one quiet, factual sentence per
// spine intent op (links / comments / contacts link ops), mirroring the Tasks
// trail (src/features/tasks/activity.ts) — a mirror, never a wall. AC4: every
// spine mutation logs an attributed `module_activity` row; this is how that row
// reads. Newest-first in the hub trail and the notification card.

import { isRelationKind, RELATION_KIND_LABELS } from "../../lib/entity-links";
import { referenceTextToPlain } from "./references/text";
import type { ReferenceRef } from "./references/types";

/** The minimal shape an activity/notification row needs to render an actor. */
export type SpineActorFields = {
  actorType?: string | null;
  actorId?: string | null;
  actorLabel?: string | null;
};

/** Who did it — "You", the recorded display name, or a quiet fallback. */
export function spineActorName(entry: SpineActorFields, currentUserId: string | null): string {
  if (entry.actorId && currentUserId && entry.actorId === currentUserId) return "You";
  if (entry.actorLabel) return entry.actorLabel;
  if (entry.actorType === "agent") return "An agent";
  if (entry.actorType === "api_key") return "An API client";
  return "Someone";
}

const str = (v: unknown): string | null => (typeof v === "string" && v ? v : null);
const num = (v: unknown): number | null => (typeof v === "number" && Number.isFinite(v) ? v : null);
/** Bytes as gigabytes for a sentence: one decimal under 10 GB, whole above. */
const gigabytes = (bytes: number): string => {
  const gb = bytes / 1073741824;
  return gb < 10 ? (Math.round(gb * 10) / 10).toString() : Math.round(gb).toString();
};

/** Phrase a relation kind for an activity line ("works at", "a follow-up"…). */
function kindPhrase(kind: string | null): string {
  if (kind && isRelationKind(kind)) {
    return (RELATION_KIND_LABELS[kind] ?? kind).toLowerCase();
  }
  return "references";
}

/**
 * The action sentence (lowercase start — rendered after the actor name).
 * Unknown ops fall back to the raw op name so the trail never lies by omission
 * when a newer client adds ops.
 */
export function spineActivityLine(
  entry: {
    op: string;
    payload?: Record<string, unknown> | null;
  },
  opts: {
    /**
     * Names a reference stored in a comment's excerpt (`moduo://task/<id>`)
     * for this reader: its title, "Private item" or "Deleted task" (RF-1).
     * Without it a reference reads "a linked item", never a title.
     */
    referenceName?: (ref: ReferenceRef) => string;
  } = {},
): string {
  const p = entry.payload ?? {};
  // A comment's excerpt stores references, never titles; name them per reader.
  const excerptText = (v: unknown): string | null => {
    const s = str(v);
    return s ? referenceTextToPlain(s, opts.referenceName) : null;
  };
  switch (entry.op) {
    case "links.create":
    case "contacts.link": {
      const kind = str(p.relation_kind);
      if (kind === "follow-up") return "added a follow-up";
      if (kind === "attachment") return "attached this";
      if (kind === "works-at") return "linked a workplace";
      if (kind === "mentions") return "mentioned this";
      return kind && kind !== "references" ? `linked this (${kindPhrase(kind)})` : "linked this";
    }
    case "links.set_kind": {
      const to = str(p.to);
      return to ? `changed a link to ${kindPhrase(to)}` : "changed a link";
    }
    case "links.delete":
    case "contacts.unlink":
      return "removed a link";
    case "comments.add": {
      const excerpt = excerptText(p.excerpt);
      return excerpt ? `commented: “${excerpt}”` : "left a comment";
    }
    // ── Tasks notifications (DF-9) ────────────────────────────────────────────
    // Generated by the tasks_notify_spine trigger, not a client op. The card's
    // target is the affected task; the actor is the assigner / the person who
    // closed the last blocker.
    case "tasks.assigned":
      return "assigned this to you";
    // TV-D1: a teammate finished a task you created.
    case "tasks.completed":
      return "completed this";
    // ── Storage alerts (AT-1): the owner's pool passed 80% / 95%. The actor is
    // whoever uploaded the file that crossed it.
    case "attachments.storage_80":
    case "attachments.storage_95": {
      const level = num(p.level) ?? (entry.op.endsWith("95") ? 95 : 80);
      const used = num(p.used_bytes);
      const total = num(p.total_bytes);
      const amounts =
        used !== null && total ? ` (${gigabytes(used)} of ${gigabytes(total)} GB)` : "";
      return `filled storage past ${level}%${amounts}`;
    }
    case "tasks.unblocked": {
      const blocker = str(p.blocker_title);
      return blocker ? `finished “${blocker}”, unblocking this` : "unblocked this";
    }
    // ── Email due (EM-6; generated by the desktop restore loop or the DF-21f web
    // sweep). Self-targeted — the actor is "You", so the verb completes "You …".
    case "email.snooze_due": {
      const subject = str(p.subject);
      return subject ? `have a snoozed email back: “${subject}”` : "have a snoozed email back";
    }
    case "email.follow_up_due": {
      const subject = str(p.subject);
      return subject ? `have a follow-up due: “${subject}”` : "have a follow-up due";
    }
    // ── Contacts module ops (logged under module='contacts') ──────────────────
    case "contacts.create":
      return "added this contact";
    case "contacts.update":
      return "updated this contact";
    case "contacts.delete":
      return "deleted this contact";
    case "contacts.restore":
      return "restored this contact";
    case "contacts.set_status": {
      const to = str(p.to);
      return to ? `set status to ${to}` : "changed the status";
    }
    case "contacts.import":
      return p.merged === true ? "updated this contact from an import" : "imported this contact";
    case "companies.create":
      return "added this company";
    case "companies.update":
      return "updated this company";
    // Chat (specs/chat.md). Only mentions + thread replies notify (quiet bar).
    case "chat.mention":
    case "chat.reply": {
      const name = str(p.channel_name);
      const where = name ? `in #${name}` : "in a direct message";
      const verb = entry.op === "chat.mention" ? "mentioned you" : "replied in a thread";
      const excerpt = str(p.excerpt);
      return excerpt ? `${verb} ${where}: “${excerpt}”` : `${verb} ${where}`;
    }
    case "chat.channel_create": {
      const name = str(p.name);
      return name ? `created #${name}` : "created a channel";
    }
    case "chat.channel_archive":
      return "archived this channel";
    case "chat.channel_unarchive":
      return "unarchived this channel";
    default:
      return entry.op;
  }
}
