import type { BrainstormOption } from "../../features/brainstorm/storage/brainstorm-storage";
import type { GridSceneOption } from "../../features/dashboard/storage/dashboard-view-storage";
import type { MindmapOption } from "../../features/mindmap/ui/mindmap-storage";
import type { MenuAnchor, TaskProjectOption } from "./app-chrome-types";

export type AppChromeMenusProps = {
  grid: {
    open: boolean;
    anchor: MenuAnchor | null;
    scenes: GridSceneOption[];
    activeSceneId: string;
    isCreating: boolean;
    newName: string;
    deleteCandidateId: string | null;
    deleteInput: string;
    deleteSubmittingId: string | null;
    closeMenu: () => void;
    setActiveScene: (sceneId: string) => void;
    setIsCreating: (value: boolean) => void;
    setNewName: (value: string) => void;
    submitCreate: () => void;
    removeScene: (sceneId: string) => void;
    setDeleteCandidateId: (value: string | null) => void;
    setDeleteInput: (value: string) => void;
    setDeleteSubmittingId: (value: string | null) => void;
  };
  tasks: {
    open: boolean;
    anchor: MenuAnchor | null;
    canEditTasks: boolean;
    projects: TaskProjectOption[];
    selectedProjectId: string | null;
    isCreating: boolean;
    newName: string;
    deleteCandidateId: string | null;
    deleteInput: string;
    deleteSubmittingId: string | null;
    closeMenu: () => void;
    setSelectedProjectId: (projectId: string | null) => void;
    setIsCreating: (value: boolean) => void;
    setNewName: (value: string) => void;
    submitCreate: () => Promise<void>;
    removeProject: (projectId: string) => Promise<void>;
    cancelDeleteIntent: () => void;
    setDeleteCandidateId: (value: string | null) => void;
    setDeleteInput: (value: string) => void;
  };
  mindmap: {
    open: boolean;
    anchor: MenuAnchor | null;
    mindmaps: MindmapOption[];
    selectedMindmapId: string | null;
    selectedWorkspaceId: string | null;
    isCreating: boolean;
    newName: string;
    deleteCandidateId: string | null;
    deleteInput: string;
    deleteSubmittingId: string | null;
    closeMenu: () => void;
    setSelectedMindmapId: (mindmapId: string | null) => void;
    setIsCreating: (value: boolean) => void;
    setNewName: (value: string) => void;
    submitCreate: () => Promise<void>;
    removeMindmap: (mindmapId: string) => Promise<void>;
    cancelDeleteIntent: () => void;
    setDeleteCandidateId: (value: string | null) => void;
    setDeleteInput: (value: string) => void;
    writeStoredActiveMindmap: (workspaceId: string | null, mindmapId: string | null) => void;
    dispatchMindmapSelectMap: (mindmapId: string | null, name?: string) => void;
  };
  brainstorm: {
    open: boolean;
    anchor: MenuAnchor | null;
    brainstorms: BrainstormOption[];
    selectedBrainstormId: string | null;
    selectedWorkspaceId: string | null;
    isCreating: boolean;
    newName: string;
    deleteCandidateId: string | null;
    deleteInput: string;
    deleteSubmittingId: string | null;
    closeMenu: () => void;
    setSelectedBrainstormId: (brainstormId: string | null) => void;
    setIsCreating: (value: boolean) => void;
    setNewName: (value: string) => void;
    submitCreate: () => Promise<void>;
    removeBrainstorm: (brainstormId: string) => Promise<void>;
    cancelDeleteIntent: () => void;
    setDeleteCandidateId: (value: string | null) => void;
    setDeleteInput: (value: string) => void;
    writeStoredActiveBrainstorm: (workspaceId: string | null, brainstormId: string | null) => void;
    dispatchBrainstormSelectView: (brainstormId: string | null, name?: string) => void;
  };
};
