import type { Meta, StoryObj } from "@storybook/react";

import { AppChromeMenus } from "./app-chrome-menus";

const meta: Meta<typeof AppChromeMenus> = {
  title: "Components/app/app-chrome-menus",
  component: AppChromeMenus,
  tags: ["autodocs"],
};

export default meta;
type Story = StoryObj<typeof meta>;

export const Primary: Story = {
  args: {
    grid: {
      open: true,
      anchor: { left: 24, top: 24 },
      scenes: [
        { id: "main", name: "Main Scene" },
        { id: "alt", name: "Alt Scene" },
      ],
      activeSceneId: "main",
      isCreating: false,
      newName: "",
      deleteCandidateId: null,
      deleteInput: "",
      deleteSubmittingId: null,
      closeMenu: () => {},
      setActiveScene: () => {},
      setIsCreating: () => {},
      setNewName: () => {},
      submitCreate: () => {},
      removeScene: () => {},
      setDeleteCandidateId: () => {},
      setDeleteInput: () => {},
      setDeleteSubmittingId: () => {},
    },
    tasks: {
      open: false,
      anchor: null,
      canEditTasks: true,
      projects: [
        {
          id: "p1",
          workspaceId: "w1",
          ownerId: "u1",
          name: "Project One",
          description: "",
          logoUrl: null,
          position: "p1",
          createdAt: new Date().toISOString(),
          updatedAt: new Date().toISOString(),
          deletedAt: null,
        },
      ],
      selectedProjectId: "p1",
      isCreating: false,
      newName: "",
      deleteCandidateId: null,
      deleteInput: "",
      deleteSubmittingId: null,
      closeMenu: () => {},
      setSelectedProjectId: () => {},
      setIsCreating: () => {},
      setNewName: () => {},
      submitCreate: async () => {},
      removeProject: async () => {},
      cancelDeleteIntent: () => {},
      setDeleteCandidateId: () => {},
      setDeleteInput: () => {},
    },
    mindmap: {
      open: false,
      anchor: null,
      mindmaps: [
        {
          id: "m1",
          workspaceId: "w1",
          ownerId: "u1",
          name: "Mindmap One",
          position: "m1",
          createdAt: new Date().toISOString(),
          updatedAt: new Date().toISOString(),
          deletedAt: null,
        },
      ],
      selectedMindmapId: "m1",
      selectedWorkspaceId: "w1",
      isCreating: false,
      newName: "",
      deleteCandidateId: null,
      deleteInput: "",
      deleteSubmittingId: null,
      closeMenu: () => {},
      setSelectedMindmapId: () => {},
      setIsCreating: () => {},
      setNewName: () => {},
      submitCreate: async () => {},
      removeMindmap: async () => {},
      cancelDeleteIntent: () => {},
      setDeleteCandidateId: () => {},
      setDeleteInput: () => {},
      writeStoredActiveMindmap: () => {},
      dispatchMindmapSelectMap: () => {},
    },
    brainstorm: {
      open: false,
      anchor: null,
      brainstorms: [
        {
          id: "b1",
          workspaceId: "w1",
          ownerId: "u1",
          name: "Brainstorm One",
          position: "b1",
          createdAt: new Date().toISOString(),
          updatedAt: new Date().toISOString(),
          deletedAt: null,
        },
      ],
      selectedBrainstormId: "b1",
      selectedWorkspaceId: "w1",
      isCreating: false,
      newName: "",
      deleteCandidateId: null,
      deleteInput: "",
      deleteSubmittingId: null,
      closeMenu: () => {},
      setSelectedBrainstormId: () => {},
      setIsCreating: () => {},
      setNewName: () => {},
      submitCreate: async () => {},
      removeBrainstorm: async () => {},
      cancelDeleteIntent: () => {},
      setDeleteCandidateId: () => {},
      setDeleteInput: () => {},
      writeStoredActiveBrainstorm: () => {},
      dispatchBrainstormSelectView: () => {},
    },
  },
};
