/**
 * Barrel re-export for the shared Zod contract layer.
 *
 * Import from `@contracts/<module>` (browser) or `../_shared/contracts/<module>.ts`
 * (Deno):
 *
 * ```ts
 * import { parseOrError, isoDateTime, uuid } from "@contracts/index";
 * // or in Deno:
 * import { parseOrError, isoDateTime, uuid } from "../_shared/contracts/index.ts";
 * ```
 */

export {
  formatZodError,
  parseOrError,
  parseOrStructured,
  type SafeParseErr,
  type SafeParseOk,
  type SafeParseResult,
  type StructuredFieldError,
} from "./errors.ts";

export {
  envString,
  httpUrl,
  isoDateTime,
  jsonString,
  nonEmptyString,
  optionalString,
  positiveInt,
  uuid,
  type EnvString,
  type HttpUrl,
  type IsoDateTime,
  type JsonString,
  type NonEmptyString,
  type OptionalString,
  type PositiveInt,
  type Uuid,
} from "./primitives.ts";

export {
  parseJsonBody,
  createCheckoutSessionBodySchema,
  createPortalSessionBodySchema,
  emailBodySchema,
  issueFounderCouponBodySchema,
  manageIntegrationBodySchema,
  manageIntegrationQuerySchema,
  notesPublicTokenSchema,
  waitlistJoinBodySchema,
  workspaceInviteWebhookBodySchema,
} from "./http-bodies.ts";

export { listingJsonSchema, parseToolArgs, TOOL_ARG_SCHEMAS } from "./mcp-tool-args.ts";

export {
  entityTypeKeyModule,
  keyCanSeeEntityType,
  keyScopeAllows,
  MCP_ENTITY_TYPE_MODULES,
  MCP_KEY_MODULE_LABELS,
  MCP_TOOL_NEEDS,
  mcpKeyScopeRank,
  mcpToolNeeds,
  type McpToolAccess,
} from "./mcp-key-scopes.ts";

export {
  activityRowSchema,
  bucketRowSchema,
  calendarAccountRowSchema,
  calendarEventRowSchema,
  calendarSyncDescriptorSchema,
  caldavCalendarSchema,
  commentRowSchema,
  companyRowSchema,
  contactFieldDefRowSchema,
  contactRowSchema,
  emailAccountRowSchema,
  emailRefRowSchema,
  entityLinkRowSchema,
  entityRecordRowSchema,
  habitRowSchema,
  jsonRpcRequestSchema,
  linkSuggestionRowSchema,
  mapKnownRows,
  noteRowSchema,
  noteUpdateRowSchema,
  notificationRowSchema,
  openMeteoForecastSchema,
  openMeteoGeocodeSchema,
  parsedCalendarProvider,
  parsedMailboxProvider,
  parsedRelationKind,
  parseRow,
  prefsRowSchema,
  publicNotePayloadSchema,
  publicNoteSchema,
  requireMapped,
  requireRow,
  tagLinkRowSchema,
  tagRowSchema,
  taskRelationRowSchema,
  taskRowSchema,
} from "./rows.ts";

export {
  ACTIVITY_ACTOR_TYPES,
  CALENDAR_ACCOUNT_STATUSES,
  CALENDAR_PROVIDERS,
  CONNECTION_STATUSES,
  CONTACT_FIELD_TYPES,
  EMAIL_ACCOUNT_STATUSES,
  EMAIL_PROVIDERS,
  ENERGY_LEVELS,
  INVITE_STATUSES,
  KNOWN_SUBSCRIPTION_STATUSES,
  LINK_ORIGINS,
  MCP_KEY_MODULES,
  MCP_KEY_SCOPES,
  MEMBER_DB_PERMISSIONS,
  MEMBER_DB_ROLES,
  MODULE_PERMISSIONS,
  PLAN_TIERS,
  PRIORITY_LEVELS,
  RELATION_KINDS,
  SYNCABLE_PROVIDERS,
  TASK_STATUSES,
  EMAIL_KINDS,
  WAITLIST_SOURCES,
  WAITLIST_STATUSES,
  WORKSPACE_ROLES,
  activityActorTypeSchema,
  calendarAccountStatusSchema,
  calendarProviderSchema,
  connectionStatusSchema,
  contactFieldTypeSchema,
  emailAccountStatusSchema,
  energyLevelSchema,
  inviteStatusSchema,
  isCalendarProvider,
  isKnownSubscriptionStatus,
  isMailboxProvider,
  isMcpKeyModule,
  isMcpKeyScope,
  isMemberDbRole,
  isPlanTier,
  isRelationKind,
  isTaskStatus,
  isEmailKind,
  isWaitlistSource,
  isWorkspaceRole,
  knownSubscriptionStatusSchema,
  linkOriginSchema,
  mailboxProviderSchema,
  mcpKeyModuleSchema,
  mcpKeyScopeSchema,
  mcpKeyScopesSchema,
  memberDbPermissionSchema,
  memberDbRoleSchema,
  modulePermissionSchema,
  normalizeCalendarProvider,
  normalizeEmailProvider,
  normalizeLinkOrigin,
  normalizeMcpKeyScope,
  normalizeMcpKeyScopes,
  normalizePlanTier,
  normalizeRelationKind,
  parseMcpKeyScope,
  parseMcpKeyScopes,
  parsePlanTier,
  planTierSchema,
  priorityLevelSchema,
  relationKindSchema,
  syncableProviderSchema,
  taskStatusSchema,
  emailKindSchema,
  waitlistSourceSchema,
  waitlistStatusSchema,
  workspaceRoleSchema,
  type ActivityActorType,
  type CalendarAccountStatus,
  type CalendarProvider,
  type ConnectionStatus,
  type ContactFieldType,
  type EmailAccountStatus,
  type EnergyLevel,
  type InviteStatus,
  type KnownSubscriptionStatus,
  type LinkOrigin,
  type MailboxProvider,
  type McpKeyModule,
  type McpKeyScope,
  type McpKeyScopes,
  type MemberDbPermission,
  type MemberDbRole,
  type ModulePermission,
  type PlanTier,
  type PriorityLevel,
  type RelationKind,
  type SyncableProvider,
  type TaskStatus,
  type EmailKind,
  type WaitlistSource,
  type WaitlistStatus,
  type WorkspaceRole,
} from "./vocabularies.ts";
