#!/usr/bin/env bun
/**
 * Regenerate docs/decisions.md (the one-line index) from the area files in
 * docs/decisions/*.md. The area file is the source of truth; nobody edits the
 * index by hand. `--check` exits 1 when the committed index is stale.
 */
import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";

const root = resolve(import.meta.dir, "..");
const dir = resolve(root, "docs/decisions");
const out = resolve(root, "docs/decisions.md");

// Reading order: cross-cutting first, then modules. New areas append alphabetically.
const ORDER = [
  "workflow",
  "permissions",
  "billing",
  "meet",
  "desktop-release",
  "toolchain",
  "email",
  "mcp",
  "calendar",
  "notes",
  "contacts",
  "dashboard",
  "data",
  "spine",
  "tasks",
  "design-system",
  "brand",
  "product",
];

const files = readdirSync(dir).filter((f) => f.endsWith(".md"));
const areas = [
  ...ORDER.filter((a) => files.includes(`${a}.md`)),
  ...files
    .map((f) => f.replace(/\.md$/, ""))
    .filter((a) => !ORDER.includes(a))
    .sort(),
];

// The first `**` after the opening one that is not inside backticks (titles quote globs like `landing/**`).
function closingBold(line: string): number {
  let inCode = false;
  for (let i = 4; i < line.length - 1; i++) {
    if (line[i] === "`") inCode = !inCode;
    else if (!inCode && line[i] === "*" && line[i + 1] === "*") return i;
  }
  return -1;
}

const sections: string[] = [];
for (const area of areas) {
  const text = readFileSync(resolve(dir, `${area}.md`), "utf8");
  const title = text.match(/^# Decisions:\s*(.+)$/m)?.[1]?.trim() ?? area;
  const lines: string[] = [];
  for (const line of text.split("\n")) {
    if (!line.startsWith("- **")) continue;
    const end = closingBold(line);
    const head = (end === -1 ? line.slice(4, 164) : line.slice(4, end)).trim();
    lines.push(`- ${head}`);
  }
  sections.push(
    `## ${title} → [decisions/${area}.md](decisions/${area}.md)\n\n${lines.join("\n")}`,
  );
}

const body = `# Decisions log (index)

<!-- GENERATED by \`bun run gen:decisions-index\` from docs/decisions/*.md. Do not edit by hand. -->

One line per locked product or architecture decision, grouped by area, newest first. The full entry lives in the area file linked in each heading. Agents don't read this index at session start: they read the **last five entries of the area file** for the area they touch. The index is for people and for search.

**Adding a decision:** write the full entry at the top of \`docs/decisions/<area>.md\` (one bold title sentence, then the why and a pointer to the authoritative doc), then run \`bun run gen:decisions-index\`. CI fails when the index is stale. If no area fits, use \`product\`.

> Migration-status clauses inside older entries ("deploy-ready but unapplied") describe the day they were written, not today. Probe the database before treating one as a task. See [decisions/data.md](decisions/data.md).

${sections.join("\n\n")}
`;

if (process.argv.includes("--check")) {
  const current = readFileSync(out, "utf8");
  if (current !== body) {
    console.error("docs/decisions.md is stale. Run: bun run gen:decisions-index");
    process.exit(1);
  }
  console.log("docs/decisions.md is current.");
} else {
  writeFileSync(out, body);
  console.log(`Wrote docs/decisions.md across ${areas.length} areas.`);
}
