-- Time-blocks for the Tasks module (improvement-plan Session 2).
--
-- One row per workspace: a slot → bucketId map ({"morning": "<uuid>", ...}),
-- mirroring the client's TimeBlockMap. Previously localStorage-only, which
-- meant the assignment was per-device and desktop lost it entirely.
--
-- NOTE: this file back-fills the repo copy of a migration that was applied to
-- the hosted project on 2026-06-11 (version 20260611132737). Hosted is the
-- ground truth; do not edit this file — write a new migration instead.

CREATE TABLE IF NOT EXISTS public.task_time_blocks (
  workspace_id uuid PRIMARY KEY REFERENCES public.workspaces(id) ON DELETE CASCADE,
  blocks       jsonb NOT NULL DEFAULT '{}'::jsonb,
  updated_at   timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.task_time_blocks ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS task_time_blocks_workspace_access ON public.task_time_blocks;
CREATE POLICY task_time_blocks_workspace_access ON public.task_time_blocks
  FOR ALL
  USING (public.tasks_module_can_access_workspace(workspace_id))
  WITH CHECK (public.tasks_module_can_access_workspace(workspace_id));
